app/models/content_item.rb, app/models/publish_intent.rb
The name was confusing because it implied that it contained the details hash
which is actually a nested item in the hash.
=> Rename variable for clarity

README.md
=> Add draft-content-store instructions to README

Gemfile.lock
__Depends on:__ https://github.com/alphagov/plek/pull/35
=> Bump Plek version to 1.11.0

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/content_item.rb, app/presenters/content_item_presenter.rb, config/routes.rb, spec/presenters/content_item_presenter_spec.rb, spec/routing/content_item_routing_spec.rb, spec/routing/publish_intent_routing_spec.rb, spec/support/request_helpers.rb
Also updates the routing to be compatible with
newer Rails versions.
Needed for https://trello.com/c/blLdEZN5/292-make-apps-register-special-routes-on-deploy
=> Accept root path

lib/tasks/data_hygiene/duplicate_report.rake, lib/tasks/data_hygiene/duplicate_report.rb, spec/factories/content_item.rb, spec/lib/tasks/data_hygiene/duplicate_report_spec.rb
Includes some minor code cleanup/clarity changes.
=> Add a simple test for the duplicate report

app/models/content_item.rb, app/models/publish_intent.rb, app/models/registerable_gone_route.rb, app/models/registerable_redirect.rb, app/models/registerable_route.rb, app/models/registerable_route_set.rb, app/models/route_set.rb, spec/factories/registerable_routes.rb, spec/factories/route_set.rb, spec/models/registerable_route_set_spec.rb, spec/models/route_set_spec.rb
Recommend reviewing commit by commit.
=> Refactor registerable routes

app/controllers/content_items_controller.rb, config/routes.rb, spec/integration/deleting_a_content_item_spec.rb, spec/service_consumers/pact_helper.rb
This allows the publishing API to remove discarded
drafts.
https://trello.com/c/YLIwrSRf/434-add-delete-endpoint-to-content-store
=> Add DELETE content endpoint.

app/queries/linked_items_query.rb, spec/models/content_item_spec.rb
Document collections have links to documents. (Whitehall) Documents
need to know which collections they belong to. This extends similar
logic that was created for working groups and policies.
https://trello.com/c/UcqLRRSu/387-add-document-collection-documents-to-placeholder
=> Inverse links for document collections

app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb
These attributes are very useful for debugging.
=> Expose publishing_app and rendering_app

app/validators/schema_validator.rb
Update the schema path to the deploy location on the relevant server.
=> Amend schemas path

app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/fetching_linked_items_spec.rb, spec/integration/public_api_request_spec.rb, spec/presenters/content_item_presenter_spec.rb
Travel advice document_types still need to go through the old flow
=> Use expanded links instead of expanding the links in the content_store

Jenkinsfile, jenkins.sh
Before merging, we need to run the following on the Jenkins script console:
def job = Jenkins.instance.getItemByFullName("content-store/master")
job.nextBuildNumber = 598
job.save()
=> Add Jenkinsfile and remove gh-status calls.

README.md, jenkins.sh, spec/service_consumers/pact_helper.rb
Pact Broker is now hosted on PAAS at
https://pact-broker.cloudapps.digital
=> Reinstate Pact Broker

lib/content_dumper.rb, lib/tasks/dump_content.rake
This will be used by the `publishing-api` consistency checker.
=> Add a content dumper

app/models/content_item.rb, app/models/update_lock.rb, db/migrate/20170427124126_remove_transmitted_at_from_content_item.rb, spec/factories/content_item.rb, spec/integration/end_to_end_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_gone_item_spec.rb, spec/integration/submitting_placeholder_item_spec.rb, spec/integration/submitting_redirect_item_spec.rb, spec/models/content_item_spec.rb, spec/models/update_lock_spec.rb, spec/service_consumers/pact_helper.rb
https://trello.com/c/fGsTnEVZ/925-remove-transmitted-at-support-from-content-store
=> Remove transmitted_at support

Jenkinsfile
https://trello.com/c/NwvQLJMs/957-run-e2e-tests-as-part-of-content-store-and-travel-advice-publisher-builds-1
=> Add params to Jenkinsfile to run Publishing e2e tests

doc/content_item_fields.md
They weren't rendering correctly before.
=> Fix headings in content item fields documentation

openapi.yaml
This fixes minor issues that were missed before.
[Trello Card](https://trello.com/c/WOxfVVNs/1021-2-add-existing-public-api-to-the-wip-documentation)
=> Fix OpenAPI specification

openapi.yaml
This includes various fixes to improve the OpenAPI documentation generation.
[Trello Card](https://trello.com/c/zO3C0fqR/1053-2-look-into-how-we-can-present-the-reference-documentation-clearer)
=> Various OpenAPI Spec fixes

openapi.yaml
https://trello.com/c/AaQa591M/1054-1-add-more-details-to-the-reference-documentation
Adds some descriptions and parameters to the docs.
Also adds a more representative response example and some schema examples.
=> Add openapi intro and description

openapi.yaml
This is from the first round of reviewing the Content API docs
=> Tweaks to Openapi.yml file

openapi.yaml
This seems somewhat nicer to view than that generated automatically by
widdleshins. Though does seem harder to maintain.
=> Add copy/pasteable code sample for openapi

openapi.yaml
[Trello Card](https://trello.com/c/7XPMle03/1105-quickish-fixes-to-documentation)
=> Change usage of eg to for example

Gemfile, Gemfile.lock, spec/factories/content_item.rb, spec/factories/publish_intent.rb, spec/factories/route_set.rb, spec/integration/deleting_a_content_item_spec.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/public_api_request_spec.rb, spec/lib/find_by_path_spec.rb, spec/lib/tasks/data_hygiene/schema_validator_spec.rb, spec/models/content_item_spec.rb, spec/presenters/content_item_presenter_spec.rb, spec/service_consumers/pact_helper.rb, spec/support/factory_bot.rb
This shushes a few deprecation warnings we're seeing.
=> Switch FactoryGirl to FactoryBot

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb
https://trello.com/c/36ZgSxPD/465-we-are-indexing-travel-advice-index-from-the-publishing-api
=> Add user_need_document_supertype

Procfile, manifest.yml
The PaaS manifest file will not have any effect for now.
=> Initial PaaS manifest

Gemfile, Gemfile.lock
Update govuk_app_config gem to pick up a fix for Statsd gauge stats.
=> Fix logging of document validation

lib/tasks/register_backends.rake
In the register backends rake task.
=> Tell the Router API to commit after changing the routes

lib/find_gsi_domain_references.rb
* Use `or` queries
* Use `details.parts.body.content` rather than `details.parts.body`
* Present a full clickable URL
=> Make some fixes to the GSI script

lib/find_specific_term.rb
Avoid needing to beg a nice developer to dig out the exported csv file by exposing the output in Jenkins.
Add simple_smart_answer question fields to things to search.
=> Dump csv output in Jenkins console

lib/find_specific_term.rb
Include description field in content store searches
=> Add detailed guide summary field

config/application.rb
We are adding support for:
Croatian: hr
Danish: da
Dutch: nl
Finish fi
Icelandic is
Irish gd
Norwegian: no
Maltese: mt
Slovenian: sl
Swedish: sv
Add the locale codes to config/application.rb to allow support for
them.
=> Add new locales

config/application.rb
Adds support for Kazakh (kk)
[Trello](https://trello.com/c/fVLk3RBY/1085-add-translation-option-for-kazakh)
=> Add new locale

lib/find_specific_term.rb
Trello: https://trello.com/c/vWLiYwuN
Finds content items were the phrase/term being searched for appears in the title.
=> Check if title contains specific term

lib/find_gsi_domain_references.rb, lib/find_specific_term.rb
Introduced in: a2c6d48618647488d483ff8ae436997d3c920528
=> Fix using system /tmp instead of Rails' one

.rubocop.yml, Rakefile, app/models/content_item.rb, db/migrate/20141203161550_fixup_manual_section_format.rb, db/migrate/20141219114603_remove_non_case_study_whitehall_unpublishings.rb, db/migrate/20150220114658_really_remove_non_case_study_whitehall_unpublishings.rb, db/migrate/20150916083409_populate_live_phase.rb, db/migrate/20151013123045_make_inconsistent_policies_into_redirects.rb, db/migrate/20151014135153_add_redirects_for_raib.rb, db/migrate/20151015100245_redirect_publications_to_statistics.rb, db/migrate/20151015103826_fix_redirects_for_schools_commissioner.rb, db/migrate/20151015111051_fix404ing_content_items.rb, db/migrate/20151015115116_fix_orgs_special_cases.rb, db/migrate/20151020130422_set_redirects_for_odd_unpublishings.rb, db/migrate/20151029154403_add_content_ids_to_email_signups.rb, db/migrate/20151110173144_add_signup_type_to_email_alert_signups.rb, db/migrate/20151113171020_replace_tags_with_signup_tags_on_email_alerts.rb, db/migrate/20151207120531_update_blank_hmrc_manuals_content_ids.rb, db/migrate/20160503152550_backfill_schema_name_and_document_type.rb, db/migrate/20161201151347_remove_deleted_content_items.rb, db/migrate/20170427124126_remove_transmitted_at_from_content_item.rb, db/migrate/20191010094643_backfill_auth_bypass_ids.rb, db/migrate/20191011142024_remove_auth_by_pass_i_ds_from_access_limited.rb, script/rails
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
=> Make entire repository pass Rubocop linting

.rubocop.yml, app/controllers/application_controller.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/publish_intent_crud_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/support/request_helpers.rb
https://github.com/alphagov/rubocop-govuk/issues/73
Please see the commits for more details.
=> Sync this repo with RuboCop GOV.UK

spec/integration/submitting_content_item_spec.rb
This test seemed to rely on the code running within 0.01 seconds which
is variable based on a number of factors. I've switched to use Timecop
to remove this environmental impact.
=> Fix flakey scheduled publishing log test

config/application.rb
Adds support for Punjabi (Pakistan) locale.
[whitehall](https://github.com/alphagov/whitehall/pull/5999)
[government-frontend](https://github.com/alphagov/government-frontend/pull/2027)
[govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas/pull/1047)
[publishing-api](https://github.com/alphagov/publishing-api/pull/1903)
[trello](https://trello.com/c/devOCero/2369-3-change-punjabi-pakistan-language-tag)
=> Add Punjabi-Pakistan locale

config/application.rb
Removes pa-ur which was superseded by pa-pk
[trello](https://trello.com/c/devOCero/2369-3-change-punjabi-pakistan-language-tag)
=> Remove pa-ur locale

README.md, docs/access-limited-content-items.md, docs/content-store-api.md, docs/content-store-read-write.md, docs/content_item_fields.md, docs/technical-information.md, startup.sh
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This follows the pattern established in [1].
Please see the commit messages for more details.
[1]: https://github.com/alphagov/content-publisher/pull/2257
=> Favour GOV.UK Docker for running the app

config/application.rb
https://trello.com/c/cSuhVSSq/2550-add-nepalese-translation-option-to-whitehall
=> Add support for Nepali (ne) language

config/application.rb
https://trello.com/c/cDsKUvYY/2652-new-translation-option-yiddish
=> Add support for Yiddish (yi) language

Dockerfile
Details as for alphagov/frontend@de3750e.
The publishing-e2e-tests failure is expected until alphagov/publishing-e2e-tests#435 is merged.
=> Multi-stage Docker build.

.github/workflows/ci.yaml
Forgive my fast/sloppy YAML engineering
Context: https://github.com/alphagov/content-store/actions/runs/1784274226/workflow
=> Fixup YAML indentation

.github/workflows/deploy.yaml
https://trello.com/c/tUyJa4cb/923-extend-gha-to-deploy-to-specific-environment
=> Update deploy.yaml to allow for better rollbacks

.github/pull_request_template.md
Trello: https://trello.com/c/aDiHro0u/26-enable-continuous-deployment-for-content-store
=> Add continuous deployment pull request template

app/lib/json_importer.rb, spec/lib/json_importer_spec.rb
[Trello card](https://trello.com/c/U4kiudWW/820-fix), _merge this into the `port-to-postgresql` branch, along with merging #1138 into `main`_
To try and stop the [mongo-to-postgres-cron-job](https://github.com/alphagov/govuk-helm-charts/blob/main/charts/govuk-jobs/templates/content-store-mongo-to-postgres-cronjob.yaml) running out of disk space in staging, we're piping the exports through gzip (#1138). This correspondingly pipes the import of that exported JSON through gunzip. It also gets rid of `batch_size` as a parameter, as it was never used in practice with any value other than 1
⚠️ This repo is Continuously Deployed: make sure you [follow the …
=> Make JsonImporter only import gzipped files

.github/workflows/deploy.yml, Dockerfile
This gets content-store built for ARM.
=> Get content-store working on ARM

config/application.rb
Trello: https://trello.com/c/T2neQSyf/3319-add-language-support-for-kyrgyz
=> Add support for Kyrgyz

.github/workflows/actionlint.yml, .github/workflows/verify-pact.yml
Bulk Update: Addresses govuk-infrastructure#1361
=> Add Actionlint Checks

app/controllers/content_items_controller.rb, app/presenters/content_item_presenter.rb, spec/presenters/content_item_presenter_spec.rb, spec/support/request_helpers.rb
This attribute is private to this class and the code that used it is long gone
=> Remove ContentItemPresenter's `api_url_method`

config/application.rb
Jira card: https://gov-uk.atlassian.net/browse/NAV-18482
=> Add support for Kurdish Sorani and Tigrinya
