doc/content_item_fields.md
The previous wording made it sound like the ContentStore used this field in some way. This new wording makes it clear that the publishing App should send the correct timestamp.
=> Clarify use of public_updated_at field

app/models/registerable_route_set.rb, spec/models/registerable_route_set_spec.rb
To prevent confusion caused if a path is included more than once.
=> Add uniqueness validation on route/redirect paths.

config/routes.rb, spec/routing/content_item_routing_spec.rb, spec/routing/publish_intent_routing_spec.rb
Using parens around a route parameter makes that param optional.  This
meant that requests for eg `/content` were being routed through to
`content_items#show`, which then errored because it expected `base_path` to be
populated.
=> Require a base_path in the routes.

app/models/content_item.rb, spec/models/content_item_spec.rb, spec/presenters/public_content_item_presenter_spec.rb
This was previously looking up available_translations using a nil content_id.  This resulted in an apparently random item being linked as the available translation (eg at the moment, "Civil Service Apprenticeship Schemes" is being returned as a translation of "VAT rates").
=> Fix translation lookup for item with no content_id

app/controllers/application_controller.rb, doc/content_item_fields.md, doc/gone_item.md, doc/publish_intents.md, doc/redirect_item.md, doc/route_registration.md
The documentation implies that the base_path must be included in the request
body for write requests as well as in the URL. This is not true and in fact if
supplied in the body it is discarded, otherwise it is ignored - the base_path
in the URL is used instead.
Leading developers to believe that it is required but not performing any
validation on it seems likely to be a source of errors, so let's get rid of it.
Once all clients have been updated to omit it from the request body, we can
stop treating it as a special case and start rejecting it as we would any other
unexpected field.
=> Deprecate base_path in body in the publishing context

db/migrate/20150220114658_really_remove_non_case_study_whitehall_unpublishings.rb
In https://github.com/alphagov/content-store/pull/96 we attempted to
remove these.
However, we ran this migration before deploying the change to whitehall
which stopped sending unpublishings for non-case-studies to the content
store (deployed 22nd dec).
Therefore, some slipped through the net.
In addition we missed out unpublishings of translated content items.
This migration cleans up the remaining unpublishings.
=> Really remove non-case-study whitehall unpublishings

app/controllers/content_items_controller.rb, app/controllers/publish_intents_controller.rb, app/presenters/private_content_item_presenter.rb, spec/integration/publish_intent_crud_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_gone_item_spec.rb, spec/integration/submitting_redirect_item_spec.rb, spec/presenters/private_content_item_presenter_spec.rb
content-store returns the entity (the thing you sent it) as part of the response document, with an `errors` key mixed in. We don't have a use-case for this and we can't think of one, other than a stateless client (but we don't think this is a strong use case). If we need it, we can add it back in.
Aside:
This change makes some other work much simpler - https://github.com/alphagov/gds-api-adapters/pull/276
=> Dont return entity in PUT responses

lib/queue_publisher.rb, spec/lib/queue_publisher_spec.rb
Change QueuePublisher to connect to rabbitmq on demand as opposed to in
the constructor. This means that the constructor won't raise an error
if rabbitmq is unavailable/unresponsive. Because this is called from an
initializer, if it raises an exception it will cause the application to
fail to boot.
=> Allow the app to boot when rabbitmq is unavailable.

config/mongoid.yml
https://trello.com/c/9IjHVbeJ
to be able to run two instances of content-store in development, one as live and other as draft, we need to be able to switch to the respective database.
intention is to set MONGO_DB_NAME envvar with value as draft_content_store_development through govuk_setenv when running the draft-content-store instance.
=> Allow mongo db name to be set from ENV

config/initializers/prepend_draft_to_logs_in_development.rb
https://trello.com/c/9IjHVbeJ
this will help distinguish between request for draft content and live content in development environment when content-store is running with DRAFT=true.
the initial thought was to write to a separate log file like: log/draft_development.log. i was able to get rails to start writing to that log in draft mode, but couldn't prevent it from writing to log/development.log. hence, resorted to this approach.
=> Prepend log entries with DRAFT

config/initializers/prepend_draft_to_logs_in_development.rb
https://trello.com/c/9IjHVbeJ
To simplify puppet code, we're checking for presence of this ENV var instead of a specific value.
=> Check for presence of ENV var DRAFT

app/models/content_item.rb, spec/factories/content_item.rb, spec/integration/end_to_end_spec.rb
This change only adds it for "renderable content" (anything but 'gone' and
'redirect' items) because there making Whitehall produce redirect items with a
(meaningful) public_updated_at is non-trivial.
=> Make public_updated_at required for renderable content

Gemfile, Gemfile.lock, lib/tasks/check_content_items_against_schema.rake
Example output:
```
$ bundle exec rake check_content_items_against_schema[case_study]
Validating 887 content items
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.....F.F...........F.................................................................................................................................................................................................... …
```
=> Add a rake task to validate content items in the database

config/routes.rb, spec/routing/content_item_routing_spec.rb
I'm shortly planning to make the content-store "GET content" API public.  As
part of that, we'd like to be very sure that only GET requests will be routed
from the public API.
To help with this, this commit adds a route to handle GET requests to
`/api/content/foo`.  This route serves exactly the same content as
`/content/foo`, but only handles GET requests.
By pointing publicapi at this route, we get some defence-in-depth that only the
read-only part of the API is available.  We also make it easier to distinguish
requests which have come via the public API from those which come from other
internal apps in log files and in systems such as Kibana.
=> Add separate GET route for the public API to use

app/controllers/content_items_controller.rb, config/routes.rb, spec/integration/fetching_content_item_spec.rb, spec/routing/content_item_routing_spec.rb
When requesting content items through the public API endpoint
(/api/content/foo), we want the API URLs returned in linked content
items to also use public API URLs.
=> Return public API URLs when from the public endpoint

config/mongoid.yml
https://trello.com/c/2ZsPnGKo
moving towards the design of configuring stuff using only
ENV vars over file uploads through capistrano, as:
https://github.com/alphagov/router-api/pull/65
content-store already uses ENV vars for setting the db name
for draft-content-store, so this change does the same for
other db configs like content-store mongodb name and uri.
this will enable us to stop uploading mongoid.yml during deploy.
=> Use MONGODB_URI from ENV var to connect to mongodb

app/models/content_item.rb, app/validators/uuid_validator.rb, spec/models/content_item_spec.rb
I tried to send a frontend example to the content store and the content
store crashed because the validation algorithm did not check whether the
content item is a string before comparing it to a regexp.
I've added a unit test for this scenario and refactored the validation
code to handle this case.
The change made is to use `#=~` rather than `Regexp#match`. Note that
`#=~` is defined on `Object` to always return false.
=> Don't crash on related links containing hashes

config/application.rb
This will allow the setting of a shorter timeout in the draft environments.
=> Enable overriding of default_ttl from env var.

Gemfile, Gemfile.lock
We want to [change the directory structure inside govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas/pull/60). The
test helpers encapsulate the directory structure, but we still need to bump the
gem to a version which works with the new (and old) structure.
=> Upgrade govuk-content-schema-test-helpers to 1.3.0

config/application.rb
When setting the cache headers, the controller calls
`config.default_ttl.from_now`.  This was triggering the following
deprecation warning because default_ttl is an integer, not an
ActiveSupport::Duration.
```
DEPRECATION WARNING: Calling #since or #from_now on a number (e.g.
5.since) is deprecated and will be removed in the future, use
5.seconds.since instead. (called from set_cache_headers at
/var/govuk/content-store/app/controllers/content_items_controller.rb:45)
```
=> Fix deprecation warning for default_ttl

app/models/content_item.rb, spec/factories/content_item.rb, spec/models/content_item_spec.rb
Presently, this only excludes redirects.  This edge case is unlikely to
be an issue at the moment because we're unlikely to have any gone items
with content ids, but it's good to make this correct.
=> Exclude all non-renderable formats from link expansion

app/models/content_item.rb, app/presenters/public_content_item_presenter.rb, spec/presenters/public_content_item_presenter_spec.rb
This is necessary to allow the rendering of mainstream browse pages (eg
https://www.gov.uk/browse/benefits) from the content-store.
This field has already been added to the schemas in
https://github.com/alphagov/govuk-content-schemas/pull/69
=> Include description in linked item expansion

doc/content_item_fields.md
Expanded links also contain the description of the content item:
https://github.com/alphagov/content-store/blob/master/app/presenters/public_content_item_presenter.rb#L28
=> Update docs for content item links

app/models/registerable_route_set.rb, doc/content_item_fields.md, doc/route_registration.md, spec/factories/registerable_routes.rb, spec/integration/submitting_content_item_spec.rb, spec/models/registerable_route_set_spec.rb
There are cases where a content item needs to provide both routes and
redirects. Most mainstream content provides a `.json` route that serves a
redirect to the public api endpoint (currently handled by the frontend
app). Multi-part content will need to support re-slugged/removed parts
by redirecting to an appropriate alternative part.
This adds support for providing redirects along with routes to
facilitate this.
=> Allow regular content items to include redirects.

README.md, app/controllers/content_items_controller.rb, app/models/content_item.rb, doc/content_item_fields.md, spec/factories/content_item.rb, spec/integration/access_limited_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/models/content_item_spec.rb
This adds support for access-limited content items in the content-store.
Content items can be marked as access-limited by including the following meta-data:
```JSON
"access_limited": {
"users": ['user-signon-uid', 'another-user-signor-uid']
}
```
Such items will only be returned to frontend applications if appropriate authentication is provided. For example:
```sh
curl -header "X-Govuk-Authenticated-User: user-signon-uid" \
https://content-store.production.alphagov.co.uk/content/government/publications/access-limited
```
Non-authorised requests will receive a 403 response.
This will be used to control access to access-limited content in the draft stack.
Trello: https://trello.com/c/fc77YcqN/173-content-store-enforces-access-limiting-if-present
=> Handling for access-limited content

spec/integration/fetching_publish_intent_spec.rb
Occasionally the test suite would fail on an expectation that the cache
timeout was exactly 300 seconds from now. Use Timecop.freeze to ensure
that no system time elapses between creating the item and verifying its
timeout.
=> Make cache test less sensitive to time.

app/models/content_item.rb, app/models/publish_intent.rb
Currently the following is being logged regularly in production:
```
Overwriting existing field _id in class ContentItem.
```
This is a warning generated by Mongoid when you define a field that's
already been defined as that's often in error.  In our case, this is
intentional because we're redefining the _id field. Adding the
`:overwrite => true` tells Mongoid that this is intentional and silences
the warning.
The `overwrite` param isn't mentioned in the documentation.  I found
mention of it in an issue on github - https://github.com/mongoid/mongoid/issues/3272
=> Fix field overwrite warnings

app/models/content_item.rb, spec/models/content_item_spec.rb
As items that are explicitly access limited are only intended for viewing by the listed individuals, and we aren't currently enforcing access limiting anywhere else, they should not be sent on the message queue.
=> Don't send access_limited items on queue.

config/initializers/message_queue.rb, lib/queue_publisher.rb, lib/tasks/heartbeat_messages.rake, spec/integration/heartbeat_message_publishing_spec.rb, spec/lib/queue_publisher_spec.rb
When queue publishing is disabled, nothing should be connecting/writing
to RabbitMQ. We therefore want the heartbeats not to be sent in this
case.
The heartbeats rake task was constructing its own QueuePublisher
instance, and therefore wasn't picking up the logic for disabling it in
the initializer.
=> Make RabbitMQ heartbeats messages respect noop mode.

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/factories/content_item.rb, spec/models/content_item_spec.rb
In order to mark an item as either Alpha or Beta a `phase` attribute
has been added. This should only be `alpha`, `beta` or `nil` and can be
used on the Frontend to alter functionality or visual elements based on
its' state.
=> Add phase to Content Item

app/models/content_item.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_placeholder_item_spec.rb, spec/models/content_item_spec.rb
In order to avoid unnecessary router reloads, we should avoid sending
routes to the router when they haven't changed.
This updates the router reload logic to take note of the previously
existing content_item, and skip registering routes, if there is a
previous item with an identical route set.
This will make most bulk re-registering processes much more efficient.
=> Only register routes for an item when they've changed.

app/models/content_item.rb
So mongoid has moved on github, and is also now using Jira for its
issues.  This means that the previous issue link was now just a 404 -
Joy!
=> Update Mongoid issue link.

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/factories/content_item.rb, spec/models/content_item_spec.rb
Analytics identifiers are short codes which we can use to represent
objects in character restricted environments (like Google Analytics
custom dimensions). Having them on the root lets us easily pull them out
to be part of the links hash so that content can be correctly marked
with all related dimensions.
=> Add analytics identifier to root object

app/models/registerable_route_set.rb, spec/models/content_item_spec.rb
`/xyz.es-419` isn’t considered part of the `/xyz` base path, so redirects
with that locale as part of the same piece of content are not
permitted. This fixes the regular expression that is used to validate
the source path
=> Allow redirects from sub-locales

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/presenters/content_item_presenter_spec.rb
So that we can correctly set any related analytics identifiers on
frontend applications expose the analytics identifiers for all the items
in the links hash if they exist.
This is the new approach since the discussions which resulted from here: https://github.com/alphagov/content-store/pull/139
https://trello.com/c/uXiRRmb1/74-send-organisation-data-to-google-analytics-for-pages-in-government-frontend-medium
=> Add analytics identifiers to links hash objects

app/models/content_item.rb, db/migrate/20150916083409_populate_live_phase.rb, spec/integration/submitting_content_item_spec.rb, spec/models/content_item_spec.rb
This also makes phase default to 'live' when not given because that's generally correct.
This PR is the implementation of alphagov/govuk-content-schemas#114
=> Allow phase to be live, and require a phase

app/models/content_item.rb, app/presenters/content_item_presenter.rb, doc/content_item_fields.md, doc/output_examples/generic.json, spec/integration/fetching_content_item_spec.rb, spec/models/content_item_spec.rb, spec/presenters/content_item_presenter_spec.rb
As described in alphagov/govuk-content-schemas#121, it's becoming
nexessary for some of the frontend applications to know about
content_ids. This exposes them in both the base item, and the expanded
links.
This includes a change to stop returning self in available translations for
an item with no content_id (see commit c89f3c2 for details)
=> Include content_id in frontend representations.

spec/integration/fetching_content_item_spec.rb
This test is currently failing on master because `phase` is "live" by default now. 
It is a mystery why this test wasn't failing earlier when the default was introduced (https://github.com/alphagov/content-store/pull/146).
=> Fix failing integration test

lib/tasks/data_hygiene.rake
`rake data_hygiene:inspect_content_ids` will give you a list of publishing apps and the number of content items with / without content_id in the database. We'll use this to verify we're sending the content_id for all documents.
Current output on my development VM:
```shell
vagrant@development:~/govuk/content-store (add-content-id-task)$ be rake data_hygiene:inspect_content_ids
frontend: 0 without, 8 with
publisher: 1719 without, 0 with
whitehall: 4652 without, 164698 with
short-url-manager: 788 without, 0 with
specialist-publisher: 48 without, 13925 with
govuk_content_api: 0 without, 1 with
static: 0 without, 12 with
collections-publisher: 450 without, 534 with
feedback: 0 without, 8 with
contacts: 134 without, 133 with
design-principles: 34 without, 3 with
contacts-admin: 0 without, 1 …
```
=> Add rake task to inspect missing content_ids

lib/tasks/data_hygiene/duplicate_report.rake, lib/tasks/data_hygiene/duplicate_report.rb
Why?
This is part of the move to using content IDs as a unique identifier for
every piece of content. Building on top of the existing CSV report,
it'd be useful to understand what the breakdown is of duplicate content
items within the EN locale. This will begin to provide some ideas about
how to approach the migration.
How?
- Extract the report logic into its own class for easier refactoring.
- Provide two different methods to produce a full list of duplicates or
a list scoped to a given locale.
=> Further improve the reporting around duplicate content ids

db/migrate/20151014135153_add_redirects_for_raib.rb, db/migrate/files/raib_redirects.csv
The pages here were redirected in router-data in https://github.gds/gds/router-data/commit/15be25b94ef6e0b12f16669d632617d8005f23a2 because it's "Rail Accident", not "Accidents".
When the redirection happened the corresponding content items have not been updated. This means that the pages on the new URLs have the same content_id. This interferes with our work to create a new tagging infrastructure.
We will remove the redirects from router-data as well: https://github.gds/gds/router-data/pull/485
Trello: https://trello.com/c/i1TwVwpN/382-fix-redirects-for-raib-pages
=> Add official redirects for RAIB pages

lib/tasks/data_hygiene/export_data.rake, lib/tasks/data_hygiene/export_data.rb
https://trello.com/c/AgfGK1lz/325-importing-existing-data
This produces a file with one JSON document per line
in ./tmp with each document having the structure:
```
{
updated_at: "2015-10-14T15:07:09+01:00",
content_item: {
content_id: "2e2d3551-4147-4136-8c0d-f0904b69c8c6",
etc..
}
}
```
These files are intended for use by the publishing
API when importing documents.
Example usage:
```
$ rake data_hygiene:export_content_items:all
Progress [====>................................................................................................] (4%)
```
=> Add rake task for exporting content items to JSON.

db/migrate/20151015115116_fix_orgs_special_cases.rb
These two pages return 404, but have the same content_id as similar pages.
- /government/world/organisations/british-trade-cultural-office-taiwan/about/recruitment is a sub page of an organisation that has been renamed in https://github.com/alphagov/whitehall/pull/2245. This subpage have not been renamed in this case. This PR fixes that.
- /government/organisations/court-of-protection seems to have existed but dissapeared. It has the same content_id as /government/organisations/court-of-protection
Trello: https://trello.com/c/cme0kKzQ/366-fix-duplicate-content-ids
=> Add redirects for previously 404'ing pages

db/migrate/20151015103826_fix_redirects_for_schools_commissioner.csv, db/migrate/20151015103826_fix_redirects_for_schools_commissioner.rb
These URLs redirect to a new spelling of the organisation, much like
the RAIB case (#154). In this case we can't find redirects in
router-data, so we assume they have been added via another way.
We need to make them redirects without content_id because the
content_id are duplicated.
Trello: https://trello.com/c/cme0kKzQ
=> Add redirects for school commissioner URLs and like pages

db/migrate/20151015100245_redirect_publications_to_statistics.csv, db/migrate/20151015100245_redirect_publications_to_statistics.rb
The publications in this CSV are being redirected by Whitehall from `/government/publications/:id` to `/government/statistics/:id`. Adding a redirect item for these fixes the problem that they have the same content_id.
Trello: https://trello.com/c/cme0kKzQ
=> Add redirects for statistics-publications

db/migrate/20151015111051_fix404ing_content_items.csv, db/migrate/20151015111051_fix404ing_content_items.rb
The paths in the CSV return 404 on the site. For example:
https://www.gov.uk/government/collections/ots-tax-complexity
However, they do have content items.
https://www.gov.uk/api/content/government/collections/ots-tax-complexity
The content_ids for these items are duplicated. In the above case it duplicates:
https://www.gov.uk/api/content/government/collections/hmt-ots-tax-complexity
Because they return 404, we think its best to remove these content items, as the items have not previously worked.
Trello: https://trello.com/c/cme0kKzQ
=> Remove content items that 404

app/models/content_item.rb, doc/content_item_fields.md, doc/gone_item.md, doc/input_examples/frontend-app/quick_answer.json, doc/input_examples/generic.json, doc/redirect_item.md, spec/factories/content_item.rb, spec/integration/end_to_end_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_gone_item_spec.rb, spec/integration/submitting_placeholder_item_spec.rb, spec/integration/submitting_redirect_item_spec.rb, spec/models/content_item_spec.rb
This was previously used in the representation which
was sent to the message bus.  This sending is now
done in the Publishing API, so Content Store no
longer uses it.
Because this was a virtual field on the content
item the field was never stored in the database.
https://trello.com/c/0vlt6iS0/355-remove-mentions-of-update-type-from-content-store
=> Remove knowledge of update type.

db/migrate/20151020130422_set_redirects_for_odd_unpublishings.csv, db/migrate/20151020130422_set_redirects_for_odd_unpublishings.rb
These special items have a duplicated content_id, but redirect to a third URL. As discussed with @rboulton it's probably best to fix these redirects here, as it's caused by a special workflow issue in
Whitehall.
=> Fix redirects for unpublishing that redirects

Gemfile, Gemfile.lock, db/migrate/20151029154403_add_content_ids_to_email_signups.rb
This is intended to be used by the email-alert-frontend to send on to the
email-alert-api, allowing policy subscriptions to be created by content
ID.
Trello: https://trello.com/c/ZD65QUBN/326-email-alerts-based-on-links-hash
=> Add data migration to include parent content ID on email signups

db/migrate/20151110173144_add_signup_type_to_email_alert_signups.rb
This will support the email-alert-frontend by providing it with the
information it needs to correctly construct a subscription request for
the email-alert-api.
=> Add email_alert_type to email signup items

db/migrate/20151113171020_replace_tags_with_signup_tags_on_email_alerts.rb
Existing email_alert_signup items currently only relate to policy alerts.
These items should be tagged with some kind of reference to the policy
they handle signups for. Currently, this reference is stored as
"details" => { "tags" => "some-policy" }. 'Tags' is not a good name in
this context. It stomps over the existing semantics for the "tags" field,
i.e. - "this piece of content is tagged to this policy".
This commit introduces a data migration to change this field to "signup_tags".
It also takes this opportunity to pluralize 'policy' for consistency with
the links attribute. This change brings the content store in line with
concurrent changes being made to policy-publisher, which handles the
presentation of all existing email_alert_signup items.
=> Change tagging of email alert signup content items

app/controllers/debug_controller.rb, config/routes.rb, lib/taggings_per_app.rb, spec/lib/taggings_per_app_spec.rb
/debug/taggings-per-app.json is a temporary endpoint which will be used to compare the taggings in panopti(con)tentapi with the taggings in the content-store.
This will aid us in the migration and will allow us to be confident that we haven't inadvertently removed any tagging.
Trello: https://trello.com/c/DLakGcP0
On content-api: https://github.com/alphagov/govuk_content_api/pull/233
=> Add a taggings-per-app endpoint

app/models/content_item.rb, app/presenters/content_item_presenter.rb, app/presenters/content_type_resolver.rb, db/migrate/20151130111755_description_value_hash.rb, spec/integration/public_api_request_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/models/content_item_spec.rb, spec/presenters/content_item_presenter_spec.rb, spec/presenters/content_type_resolver_spec.rb
https://trello.com/c/nkofgTdj/372-govspeak-part-2-move-contenttyperesolver-to-a-presenter-in-the-contentstore
This is the other half of the govspeak story. We decided that it would be better to move the content type resolution into the content store presentation layer.
This pull request includes a data migration that is quite slow (~8 minutes), so I've made sure that the implementation is backwards compatible whilst it is migrating.
We can remove that backwards compatibility in a separate pull request later.
The publishing api pull request is here: https://github.com/alphagov/publishing-api/pull/156
This pull request needs to be merged first.
=> Content type presentation

app/controllers/application_controller.rb, app/controllers/content_items_controller.rb, app/controllers/linked_items_controller.rb, app/models/content_item.rb, app/presenters/content_item_presenter.rb, app/presenters/incoming_links_presenter.rb, app/presenters/linked_item_presenter.rb, config/routes.rb, spec/integration/fetching_linked_items_spec.rb, spec/presenters/content_item_presenter_spec.rb, spec/presenters/linked_item_presenter_spec.rb
The `/incoming-links` endpoint can be used to get the "incoming" links for a content item.
It will be used by the collections to display a list of pages tagged to a particular topic.
There was some discussion beforehand about this, see RFC 37:
https://gov-uk.atlassian.net/wiki/display/FS/RFC+37%3A+Add+linked+items+to+content+items#
Related Trello ticket: https://trello.com/c/bsZAwZ35
=> Add endpoint for an item's incoming links

lib/tasks/data_hygiene/draft_content_id_cleanup.rake, lib/tasks/data_hygiene/locale_base_path_cleanup.rake
**TL;DR** Make mismatching content_ids match in both content stores.
We have content items for the same `base_path` in both content stores which do not have matching `content_id`s, this could be the result of formats changing, in most cases this appears to be a format change like `placeholder_specialist_publication` changing to `specialist_publication`, the theory being that if the draft has been updated to a `gone` or `redirect` then modified to the new format the `content_id` will have changed on the draft content store for the given `base_path`.
There are also a handful of cases where non-english locale suffixes are not present on `base_path`, this PR also adds a task to handle this.
=> Fix content_id mismatches between draft and live content stores

lib/tasks/data_hygiene/missing_attributes.rake, lib/tasks/data_hygiene/whitehall_report.rake, lib/tasks/data_hygiene/whitehall_report.rb
These are some rake tasks that we intend to use for the data cleanup work where content store will be set to a valid state, i.e. all content items have content_ids and public_updated_at timestamps. We will then export this data to a JSON file and import it into the Publishing API.
=> Data cleanup

lib/tasks/data_hygiene/locale_base_path_cleanup.rake
This fixes a minor bug where the routes and redirect paths were doubled up on translation suffixes, e.g:
/government/organisations/driver-and-vehicle-licensing-agency/about/welsh-language-scheme**.cy.cy**
=> Fix a bug with side-effects and mutating the routes/redirects array

app/models/content_item.rb, app/presenters/linked_item_presenter.rb, spec/integration/fetching_content_item_spec.rb, spec/models/content_item_spec.rb
This allows the publishing API to provide
"hard-coded" content for linked items in the cases
where we cannot currently represent them as dynamic
items in the publishing API, for example governments
(for history mode).
This is a temporary measure until a publishing API
refactor takes over the expansion of these links
hashes.
https://trello.com/c/ZahFZJR3/510-pass-through-expanded-links
=> Pass through links hashes

app/models/content_item.rb, app/presenters/linked_item_presenter.rb, spec/integration/fetching_content_item_spec.rb, spec/presenters/linked_item_presenter_spec.rb
The start and end dates for Topical Events are needed to render Topical
Event About Pages. We expand these fields in the links hash to simplify
the logic in the frontend.
We need to remove the returned field filter for linked items in order
to achieve this, as changing these `only` lines for each format is not
sustainable.
We benchmarked the removal of the `only` lines from the queries, and also
tried using `without("details.body")` which is apparently slower (thanks, Mongo(id)?).
```
Benchmark.bm(15) do |x|
x.report("only") { 1000.times { ContentItem.only(:content_id, :locale, :base_path, :title, :description).first.to_json } }
x.report("without body") { 1000.times { ContentItem.without("details.body").first.to_json } }
x.report("all") { 1000.times { ContentItem.first.to_json } }
end …
```
=> Expand extra fields for Topical Events in links hash

lib/taggings_per_app.rb, spec/lib/taggings_per_app_spec.rb
Currently the debug taggings-per-app endpoint returns the taggings of all content items, including the (mostly empty) taggings for redirects. This causes the tagging migration verifier to think that there are differences between contentapi and content-store. This is because contentapi does filter for `live` content: https://github.com/alphagov/govuk_content_api/blob/master/lib/taggings_per_app.rb#L30
We are only interested in the taggings of renderable items, not redirects.
Trello: https://trello.com/c/1QMuBOSN
=> Only return renderable content for debug endpoint

config/environments/production.rb, config/environments/test.rb
This avoids deprecation warnings like:
> DEPRECATION WARNING: The configuration option
`config.serve_static_assets` has been renamed to
`config.serve_static_files` to clarify its role (it merely enables
serving everything in the `public` folder and is unrelated to the
asset pipeline). The `serve_static_assets` alias will be removed in
Rails 5.0. Please migrate your configuration files
accordingly.
=> Change assets config to future-proof version

app/models/content_item.rb, app/models/update_lock.rb, db/migrate/20160224143207_add_default_payload_version_to_content_items.rb, spec/factories/content_item.rb, spec/integration/end_to_end_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_gone_item_spec.rb, spec/integration/submitting_placeholder_item_spec.rb, spec/integration/submitting_redirect_item_spec.rb, spec/models/content_item_spec.rb, spec/models/update_lock_spec.rb
This PR adds support for `payload_version` without yet deprecating `transmitted_at`. This will allow us to update Publishing API to start sending `payload_version` after which `transmitted_at` can be removed.
`payload_version` is essentially a locking mechanism between Publishing API and Content Store to prevent out of order 'old' content overwriting a newer version. This can be caused during the asynchronous queueing of payloads on their way from Publishing API. It will be set on the content item payloads as they are queued in Publishing API.
I've not updated the pact tests as yet but will do that when `transmitted_at` is added to Publishing API and then removed from Content Store in subsequent PRs.
[Trello](https://trello.com/c/dBmI96gI/304-change-locking-criteria-on-content-store)
=> Support `payload_version` in `ContentItem`

app/models/content_item.rb, app/queries/linked_items_query.rb, spec/models/content_item_spec.rb
The interesting change is in the last commit.
To render a working_group, you need the list of policies which link to that
working_group.
We could fulfill that by adding special knowledge to the frontend so that it
knows to make a second request, to /incoming-links. There are a few issues with
that:
* one of the design goals of the content-store is that it includes everything
needed to render that page
* it complicates the frontend
* we think that when dependency resolution is implemented, the API of
content-store will change to match this implementation, and that the
/incoming-links endpoint could be removed
If the API design does change in this way, then we don't need to do anything to
our frontends when we implement dependency resolution.
I'd rather it wasn't so directly hardcoded - …
=> Include specific incoming links in content

README.md, doc/technical-information.md
https://trello.com/c/lnd0eQu5/667-document-applications-ready-for-pentest
Breaks some deeper technical info into a separate document and brings the readme in line with the style guide.
=> Update readme to conform to styleguide

app/presenters/content_type_resolver.rb, spec/presenters/content_type_resolver_spec.rb
Such as PDF attachments.
Fixes https://errbit.publishing.service.gov.uk/apps/537de1230da115fb25004224/problems/570f522a65786378ecdd0900
=> Resolve arrays with regular content types.

app/models/content_item.rb, app/presenters/content_item_presenter.rb, doc/content_item_fields.md, doc/input_examples/generic.json, doc/output_examples/generic.json, spec/integration/fetching_content_item_spec.rb
This is a new field in the publishing API which
seems more sensible to send through to the content
store rather than skip it in the publishing API.
https://trello.com/c/Si54omdL/698-return-the-first-published-at-time-to-publishing-apps-for-content-items
=> Add first_published_at

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb, spec/presenters/content_item_presenter_spec.rb
Part of https://trello.com/c/Ahj9lNB0/645-4-update-content-items-whose-dependencies-have-changed
Expanded links are resolved in the publishing api and passed
to the content store ready for presentation. This change adds
the necessary model and presentation logic to do this.
=> Make expanded_links presentable

db/migrate/20160503152550_backfill_schema_name_and_document_type.rb
As part of the split of format into schema_name and document_type, we
need to have consistent data in content store. For newer items pushed
to content store from publishing api, the schema_name and document_type
are defaulted to format if they’re not provided in the content item in
the publishing api. This backfills other content items in content store
to have the same data.
This migration takes about a minute to run on the VM. It shouldn’t
block other operations.
/cc @danielroseman @elliotcm
=> Fill schema_name and document_type with format

app/models/content_item.rb, app/presenters/content_item_presenter.rb, app/presenters/linked_item_presenter.rb, app/queries/linked_items_query.rb, spec/factories/content_item.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/fetching_linked_items_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_gone_item_spec.rb, spec/integration/submitting_placeholder_item_spec.rb, spec/integration/submitting_redirect_item_spec.rb, spec/models/content_item_spec.rb, spec/presenters/linked_item_presenter_spec.rb
Companion to https://github.com/alphagov/whitehall/pull/2572. Best reviewed commit by commit.
The `format` field is being replaced by `schema_name` and `document_type`. The new fields have been backfilled in #207. This PR changes content store to use the new fields to inform its behaviour around linked items and route registration. It also exposes the new fields in expanded links.
This work is required to enable the migration of HTML publications from Whitehall to the new world. 
/cc @danielroseman @gpeng
=> Split format into schema name and document type

app/presenters/linked_item_presenter.rb, spec/presenters/linked_item_presenter_spec.rb
Exposes the brand and logo details for linked organisations. These are needed for HTML Publications
/cc @fofr @gpeng
=> Expand linked organisation branding

doc/technical-information.md
A number of links in this document were referring to docs in the `doc` subdirectory (which is now the file's parent directory).  I suspect this content may once have been part of the `README` and has since been moved.
The rendered file is at https://github.com/alphagov/content-store/blob/master/doc/technical-information.md
=> Fix relative links in docs

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb
Withdrawing content in a publishing application should mean the content store presents the explanation and time of the withdrawal.
Part of https://trello.com/c/78Q9mrDe/708-make-whitehall-use-unpublishing-endpoint-medium
=> Store and present ContentItem#withdrawn_notice

app/presenters/linked_item_presenter.rb, spec/factories/content_item.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/fetching_linked_items_spec.rb, spec/presenters/linked_item_presenter_spec.rb
Relies on https://github.com/alphagov/publishing-api/pull/343
As part of https://trello.com/c/ZWU9N8Bc/414-add-missing-details-to-document-list-for-document-collection-format-medium
=> Add public_updated_at to linked item presenter

app/models/content_item.rb
The `content-store` queries for this field when searching for detailed guides (and presumably other documents). Queries run in about 4-5 seconds, i.e.
```bash
$ mongo content_store_development
> db.content_items.find({ "links.documents": { "$in": ["5f1856a9-7631-11e4-a3cb-005056011aef"] } })
```
Adding an index appears to fix it.
The indexes will be [created automatically on deployment](https://github.com/alphagov/govuk-app-deployment/blob/master/content-store/config/deploy.rb#L21), but if you want to test this locally you can manually create them using:
```
bundle exec rake db:mongoid:create_indexes
```
=> Add "links.documents" index to content_items

app/models/content_item.rb, app/presenters/linked_item_presenter.rb, spec/models/content_item_spec.rb, spec/presenters/linked_item_presenter_spec.rb
Links are expanded in the publishing API, so there is no need to
expand them in the content store.
=> Do not present links when they have already been expanded

Gemfile, Gemfile.lock, lib/compare_links.rb, lib/tasks/compare.rake
Uses HashDiff to print out the differences of links and expanded_links
to ensure there are no breaking changes
=> Rake task to compare links with expanded links

lib/compare_links.rb
It is not loaded when running a rake task to compare links
=> Require Pretty-printer

lib/compare_links.rb, lib/tasks/compare.rake
These (api_url and web_url) fail on integration since the copy of the DB is from production
with production URLs.
Add show method to more easily compare links with expanded links
Change to HashDiff#best_diff which shows more precise differences with nested arrays of hashes
=> Ignore api_url and web_url

app/models/content_item.rb
The `content-store` queries for this field when searching for guides. Queries run slowly, here's an example:
```bash
$ mongo content_store_development
> db.content_items.find({ "links.working_groups": { "$in": ["f3a2c385-2a22-47db-a532-0c343315caa3"] } })
```
Adding an index appears to fix it. Dependency resolution will also fix this, after which we may remove it.
The indexes will be [created automatically on deployment](https://github.com/alphagov/govuk-app-deployment/blob/master/content-store/config/deploy.rb#L21), but if you want to test this locally you can manually create them using:
```
bundle exec rake db:mongoid:create_indexes
```
Prior art: https://github.com/alphagov/content-store/pull/215
=> Add "links.working_groups" index to content_items

lib/tasks/compare.rake
As per https://github.com/alphagov/publishing-api/pull/403/commits/21e6d26b285e97c2c5da136e0f1066cd1957668c we're switching the rake task to match use of document_type over schema_name
=> Switch schema_name to document_type

lib/compare_links.rb
This removes noise from the diff, where its just the position of the element in
the array that differs.
The ordering of the elements is non-deterministic in the content store and
publishing API, as far as I can tell.
=> Sort the array of links

doc/content_item_fields.md
Hopefully this might help people to choose between the two fields in a frontend.
=> Add to `public_updated_at` and `updated_at` documentation

app/controllers/application_controller.rb, app/controllers/content_items_controller.rb, app/validators/schema_validator.rb, spec/controllers/content_items_controller_spec.rb, spec/validators/schema_validator_spec.rb
https://trello.com/c/qegWyQTI/725-content-store-validation-against-front-end-schemas
Validates the outgoing presentation of a content item against the relevant frontend schema.
Validation errors are reported via Airbrake.
This should go out with https://github.gds/gds/alphagov-deployment/pull/1204 in order to take Airbrake notification out of the request process.
=> Validate against frontend schemas

.rubocop.yml, lib/tasks/data_hygiene/schema_validation.rake, lib/tasks/data_hygiene/schema_validator.rb, spec/integration/access_limited_spec.rb, spec/lib/tasks/data_hygiene/schema_validator_spec.rb
Adds a task which will validate all content items of a given `format`/`schema_name`/`document_type` against the relevant frontend schema.
This task reports errors for a content item `base_path` in csv format, written to the application tmp dir.
=> Add a task to validate against frontend schemas

app/models/content_item.rb, spec/factories/content_item.rb, spec/integration/fetching_content_item_spec.rb, spec/models/content_item_spec.rb
Currently sending a `gone` item through the `/unpublish` endpoint of Publishing API always creates a `gone` route in the router and causes Content Store to also return a 410 status.
Due to the vagueries of Whitehall 'unpublishing' we need a way to unpublish but still render an explanation and optional alternative url. This can't be done with a 410 route in the router.
We need to address this properly but for now this change should allow the item to be rendered correctly and fix the issues we have in production.
=> Allow `gone` items to be returned with 200

app/models/content_item.rb, spec/factories/content_item.rb, spec/models/content_item_spec.rb
A previous PR added a check for the absence of the `details` field on a `gone` content item and used that to determine whether to consider the item actually 'gone' (return 410) or gone with content (and return 200).
This PR adds further logic to that to check that there is a `details` field and that there are values within it. If there are no values we return 410 even if there are keys but they are empty.
\cc: @tuzz
=> Consider `gone` items with no explanation/alternative_url as 'gone'

config/initializers/logstasher.rb
The presence of a value for this can be used to distinguish requests
that are a product of dependency resolution in the Publishing API, and
those that are not.
The value indicates the content id of the source of the dependency
resolution activity.
=> Log Publishing-Source-Dependent-Content-Id header

spec/integration/fetching_linked_items_spec.rb
Initially it appeared that my local timezone was leaking in to the test,
and causing the public_updated_at values to differ by an hour in the
actual and expected response. I tried quite a few different ways of
resolving this, and some worked, but led to the times sometimes being a
millisecond apart.
Changing to using travel_to (instead of Timecop) and comparing against
the values from the created objects was the only way I could get the
test to pass reliably.
I was expecting that just comparing against the values on the objects
would resolve any issues, but, the rendering of the time differed. I
think the value of public_updated_at used to construct the request body
in the presenter may come directly from the factory, but in the test,
the value comes from the database, which is leading to …
=> Fix a test in the fetching linked items spec

config/environments/production.rb
The library is not loaded so this config causes an error if not removed.
=> We don't use ActionMailer.

app/models/content_item.rb, db/migrate/20141126123135_add_locale_to_existing_content.rb
This started as freezing the constant but then @dougdroper pointed out that the constant isn't actually used.
=> Remove code that is no longer used

app/presenters/content_item_presenter.rb, app/presenters/expanded_links_presenter.rb, spec/presenters/expanded_links_presenter_spec.rb
We have a problem that due to data syncing the values of `web_url` and `api_url` in the expanded links of a content item reference the production environment. This causes problems for links in the staging and integration environment.
The ideal way forward is for rendering applications to no longer use urls and instead use the absolute paths of base_path and api_path, therefore we plan to deprecate these fields from the content store.
In the meantime though this dynamically sets web_url and api_url based off Plek to be relevant to the environment the content store is running within.
=> Plek based link urls

app/models/route_set.rb, spec/support/router_helpers.rb
@jennyd pointed this out last week - I think this exists from a time when the router couldn't handle HTTPS backends. It can now because we do HTTPS to Trade Tariff and Licensing.
https://github.com/alphagov/router/commit/7e72e8b073bedb05866a0bd68e76ffdac2af7f1e
This will cause new registrations to use the HTTPS backend which will encrypt traffic in our network.
=> Remove force_http when registering a backend

config/initializers/logstasher.rb
This comes from the discussion regarding the
GOVUK-Dependency-Resolution-Source-Content-Id header at the Publishing
API Cross Team Architecture Chat meeting, in which it was mentioned that
keeping the GOV.UK specific data prefixed would be helpful when using
Kibana.
=> Keep the govuk prefix when using logstasher

app/models/content_item.rb
The calling code was removed in https://github.com/alphagov/content-store/pull/244.
cc @danielroseman
=> Remove unused method

Gemfile, Gemfile.lock, jenkins-schema.sh, jenkins.sh, spec/factories/content_item.rb, spec/presenters/content_item_presenter_spec.rb, spec/support/schema_testing.rb
This adds a test that the output of `ContentItemPresenter` is valid against the `generic` schema. This will ensure that the schemas and this app will be kept in sync.
https://trello.com/c/C8A9bnuO
=> Add a little bit of schema validation for output

db/migrate/20161201151347_remove_deleted_content_items.rb
Adds a migration to delete a number of content items. The items are `HtmlAttachment`s that have been published from Whitehall but are in fact deleted and should not be in the content store. They all currently 404 so these items need to be removed before we switch the rendering of `HtmlAttachment` content to content-store -> government-frontend.
=> Remove deleted content items

app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb
This stops content store from exposing `format` to users. This attribute is deprecated in favour of `schema_name` and `document_type`.
Removing the attribute from the database is out of scope for this PR.
https://github.com/alphagov/govuk-content-schemas/pull/444 removes the attribute from the frontend schemas.
https://trello.com/c/C8A9bnuO
cc @danielroseman is this sensible?
=> Don't expose `format`

app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb
Reverts alphagov/content-store#250.
There are some errors on multipage-frontend related to this. We'll solve those before proceeding with this.
=> Revert "Don't expose `format`"

lib/tasks/check_content_items_against_schema.rake
There's too many resuts to continue sorting them.
This commit aims to solve the following error message:
> Mongo::Error::OperationFailure: too much data for sort() with no index.
add an index or specify a smaller limit (10128)
=> Remove sorting results during verification task

lib/tasks/check_content_items_against_schema.rake
Since https://github.com/alphagov/govuk-content-schema-test-helpers/commit/bc8682bc3072cc2e66d98b698b19e06ca93f1ddf
This class receives 3 arguments, being the second the name of the
variant.
=> Fix Verification task

lib/tasks/pact.rake
This has been changed in the Publishing API in b29dc4d1 and this is the
coresponding change in the content-store where the pact with the
Publishing API is verified.
=> Remove special case for pact version

app/controllers/content_items_controller.rb, app/models/content_item.rb, spec/factories/content_item.rb, spec/integration/access_limited_spec.rb, spec/integration/fetching_content_item_spec.rb
If a valid JWT token is passed to authenticating-proxy it will extract
the value to the Govuk-Fact-Check-Id header, which is passed downstream
by gds-api-adapters.
This change then checks that the header value matches a value in the
fact_check_id array within the access_limited hash of the item being
requested and returns it if so, otherwise sends a 403.
Note that the presence of the header means the user has bypassed
normal authentication, so we need to verify that they've specifically
requested the item with that fact_check_id, and not fall through to
the auth check.
As with a normal access-limited item, we send a cache-control: private
header when the request contains the content-id header.
=> Allow fact check access via header

app/models/content_consistency_checker.rb, lib/tasks/check_content_consistency.rake, spec/models/content_consistency_checker_spec.rb
This PR adds a script to check for content consistency across the `content-store` and `router-api`.
See alphagov/publishing-api#742 for the equivalent script in the `publishing-api`.
=> Add a script to check for content consistency with router-api

app/models/content_item.rb, spec/factories/content_item.rb, spec/integration/access_limited_spec.rb, spec/models/content_item_spec.rb
Fixes an edge case around the viewing of fact-check access-limited
content items. Authenticated users were prevented from viewing
documents when a fact-check-id was set in the access-limited hash.
=> Allow authorised users to view fact-check limited content

app/models/content_item.rb, app/models/route_set.rb
Yeah... this kinda sucks. Sorry.
In the previous hack to get `gone` working with a rendering application
due to the presence of details there is a problem that the rendering_app
isn't included.
This is a fix for this by implicitly setting this value to
"whitehall-frontend" when we have a gone and a lack of rendering_app.
The alternative approach to this would be to allow the gone schema to
include a rendering_app value and send the rendering_app as part of the
PublishingAPI GonePresenter. This however felt even more wrong than this
hack as we'd have to either do:
a) Include rendering_app in all gone content items even though all
except whitehall-frontend would not be rendered by the app we are
providing (they are handled by the router)
or
b) only include rendering_app for …
=> Extend the gone but not gone hack

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb
These were added in https://github.com/alphagov/publishing-api/pull/805.
Somehow our testing system didn't pick up that content store would reject these requests. I'm planning to look into getting that fixed.
https://trello.com/c/07lAcDtC
=> Add support for supertypes to content item

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb
These are required to enabled the migration of email
subscriptions to email_alert_api.
=> Add "email" and "government" supertypes

Gemfile, Gemfile.lock, app/controllers/content_items_controller.rb, app/models/content_item.rb, config/initializers/gds_api_adapters.rb, lib/tasks/data_hygiene/inconsistent_redirect_finder.rb, spec/factories/content_item.rb, spec/integration/access_limited_spec.rb, spec/models/content_item_spec.rb
Content needs to be previewable by users without signon accounts in most stages of a publishers workflow, not just during fact check.
https://trello.com/c/7oRBYwnn/690-rename-fact-check-id-to-auth-bypass-id
=> Rename fact_check_ids to auth_bypass_ids

config/unicorn.rb
This was deployed as a secret, but doesn’t contain any credentials.
Moving it into the application itself allows us to remove app-specific
config from `alphagov-deployment`
=> Move "secret" unicorn config into application

db/migrate/20170328121315_remove_land_registry.rb
Adds a migration to remove Land Registry Corporate Information Page.
There are two content ids associated with the same base path, so these are both removed. When Whitehall republishes the document, it should push everything through correctly.
Corresponding PRs in 
* Publishing Api: https://github.com/alphagov/publishing-api/pull/869
* Whitehall: https://github.com/alphagov/whitehall/pull/3145
=> Remove Land Registry Corporate Information Page

spec/service_consumers/pact_helper.rb
Previously if the value ENV['PUBLISHING_API_PACT_VERSION'] contained a
slash the Pact URL would 404, usage of CGI.escape will percent encode
non URI characters.
The usage of URI.escape has been updated in the url variable also as I
think the original author meant the effects of CGI.escape all along.
=> Escape segments of Pact URL

spec/service_consumers/pact_helper.rb
The switch from URI.escape to CGI.escape had the unfortunate side effect
that the URLs broke when they had spaces in them as CGI.escape uses the
"+" encoding of query strings rather than the %20 used in paths. To get
this we have to use a different method and the ERB::Util.url_encode
seems to be the best option in std lib.
It worked this tiem, promise: https://ci.integration.publishing.service.gov.uk/job/publishing-api/job/docs%252Ffix-pact-testing/8/console
=> Switch from CGI.escape to ERB url_encode

lib/route_consistency_checker.rb
We can first check whether the handler is listed as backend because otherwise the backend ID will be empty.
[Trello card](https://trello.com/c/0uqM1YHL/899-create-alert-for-new-inconsistent-documents-3)
=> Avoid unnecessary backend ID checks

lib/tasks/register_backends.rake
This provides a convinient way to set backends in the Router API, for
all the content in the Content Store.
This can be useful for a few reasons:
- You have changed the configuration of the
content store with respect to the backends it generates, and want to
update the Router API.
- The data in the Router API doesn't match, as you have loaded the
database from another a deployment of these applications with
different configuration.
=> Add register_backends rake task

lib/route_consistency_checker.rb
Previously when 'route.backend_id' was nil, it was raising a NoMethodError.
[Trello card](https://trello.com/c/0uqM1YHL/899-create-alert-for-new-inconsistent-documents-3)
=> Switch to using present? to add a nil check

app/models/content_item.rb, config/application.rb, spec/integration/submitting_content_item_spec.rb
Register routes more reliably by trying multiple times and rolling back the content item if it eventually fails.
[Trello Card](https://trello.com/c/1M8bgdQ0/928-ensure-the-content-store-reliably-updates-the-router-api-3)
=> Reliably register routes

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/factories/content_item.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/submitting_content_item_spec.rb
This will be sent by the Publishing API.
[Trello Card](https://trello.com/c/JZ5Zabe9/702-remove-publishing-request-id-from-travel-advice-publisher-details-hash-2)
=> Store the GOVUK-Request-ID header in the content item

app/models/publish_intent.rb, spec/models/publish_intent_spec.rb
This commit increases the cache leeway for `PublishIntent` to 5 minutes. This has the effect of setting the max-age headers to 0 for content that has a publish intent for responses to requests received for up to 5 minutes after the scheduled publication time.
This change is being made following a perceived delay in the publishing of a statistics publication from Whitehall. Examination of the logs show that the publish request was initially sent from Whitehall within 15 seconds of the scheduled publication time but was held up, probably due
to a backlog of sidekiq jobs in the downstream queue at publishing api, and didn't arrive at content-store until over 2 minutes after the scheduled time. This caused users that tried to access the content during that time to be served the default 30 …
=> Increase publish intent cache leeway

app/controllers/content_items_controller.rb, spec/integration/submitting_content_item_spec.rb
We need data on the time it takes for scheduled publications to reach
the frontend to ensure that we are publishing sufficiently quickly to
meet statuatory requirements.
This PR records the difference between intended publish time and the
actual time that content arrives at content store to statsd.
In order to only log the latency for content submissions that relate to
a PublishIntent, we also delete the PublishIntent if we match one. This
prevents unscheduled submissions later in the day from also recording a
latency. This would give us incorrect data as the latency could be as
long as hours.
=> Log the delay in scheduled publishing

app/presenters/expanded_links_presenter.rb, spec/presenters/expanded_links_presenter_spec.rb
Some link types are base_path less e.g. contact, government and world_location. Presenting `null` `api_path`, `web_url` and `api_url` for these formats makes them invalid with the frontend schemas.
This commit removes those fields when their value is null.
=> Support base_path less content

lib/tasks/check_route_consistency.rake
When running in a rake task, Airbrake.notify doesn't properly
finish triggering before the rake task ends and therefore the
message never makes it to Airbrake.
[Trello Card](https://trello.com/c/wg6F6Gk3/947-3-investigate-why-the-inconsistent-checker-is-not-working-all-the-time)
=> Use Airbrake.notify_sync instead of Airbrake.notify

app/controllers/content_items_controller.rb, app/models/scheduled_publishing_log_entry.rb, spec/integration/submitting_content_item_spec.rb, spec/models/scheduled_publishing_log_entry_spec.rb
We need to understand how long after the time a scheduled publication is due to be published it is visible to users.
We previously tried to record this delay using statsd but the relatively low frequency of data points makes the data collected with that approach difficult to analyse. It also doesn't give us data on specific content items in the event that there is a delay in publishing and we are required to report on it by the publishers.
This PR removes the statsd logging and replaces it with logging to the database via the `ScheduledPublishingLogEntry` object. This should have a minimal effect on performance as the `update` action is relatively low traffic.
[Trello](https://trello.com/c/up4fXkoi/899-time-to-publish-for-scheduled-publishing-needs-to-be-measured)
=> Log publishing delay for scheduled publishing

Jenkinsfile
The `publishingE2eTests` option name has changed to `publishingE2ETests` in
Puppet, so we update it here to make it compatible with the change.
=> Update publishingE2ETests option name in Jenkinsfile

openapi.yaml
This will be used to generate documentation.
[Trello Card](https://trello.com/c/WOxfVVNs/1021-2-add-existing-public-api-to-the-wip-documentation)
=> Add an OpenAPI definition of the v1 API

lib/tasks/validate_content_against_schema.rake
The content-store currently returns a lot of invalid items. Before we start fixing that we need some way to track the number of invalid things.
This commit adds a rake task that is meant to be run periodically. It will take 100 items for each schema and validate those. The result is outputted so that we can see the errors in Jenkins. The overall result is sent to statsd as a gauge. This means we can generate a graph of the (sampled) percentage of content items that are invalid.
Ideally we would check every item in the content-store, but this is prohibitively expensive (it takes about 4 hours). The sample will hopefully give us enough data to start working on improving the state of the data.
https://trello.com/c/FesP8XSc
=> Add rake task to validate a sample of content

lib/tasks/validate_content_against_schema.rake
This increases the number of content items that are checked in the sampled test. The current task finishes in 36 seconds, so this will increase the runtime to around 6 minutes, which is fine.
cc @thomasleese
=> Check 100 content items per schema

Gemfile, Gemfile.lock, app/models/content_item.rb, db/migrate/20170822104138_remove_obselete_content_items_index.rb
https://trello.com/c/g4UUDLjs/1009-5-remove-long-content-store-index
Removes the mongodb index `content_id_1_locale_1_format_1_updated_at_-1_title_1__id_1` on the content items collection. The name is too long to allow upgrade to mongodb 2.6 and the index is not required by this app.
It was necessary to upgrade the `mongoid_rails_migrations` gem in order to get around the removal of the `alias_method_chain` method in Rails 5. The maintainers haven't yet accepted a fix for this so we're using the same branch as detailed in [this commit](https://github.com/alphagov/manuals-publisher/commit/598f6692a0e805dbc0625a5bf4329a298c728d42).
=> Remove obselete content items index

app/models/content_item.rb
This was broken in Whitehall – no explanation or
alternative url was being shown. This is working
in government-frontend and we're trying to move
the frontend rendering logic there anyway.
This was discovered while doing QA for the
Whitehall rails upgrade:
https://trello.com/c/eg61wStW/4-upgrade-whitehall-to-a-supported-version-of-rails
=> Fall back to government-frontend instead of whitehall for gones

openapi.yaml
After feedback from a developer who is not familiar with publishing platform
terminology, we attempt to make it clear in the documentation that links refer
to links to GOV.UK content.
https://trello.com/c/tsv24HQ8/1068-05-documentation-improvements-based-on-initial-feedback
=> Improve references to links in documentation

openapi.yaml
https://trello.com/c/B62dFYcP/1106-content-fixes-for-documentation
This (hopefully) fulfills the "Explain better" aspect of improving the documentation. I'm hopeful that these sections will also have links to a soon arriving "Getting Started" section which can explain these difficult concepts better.
=> Improve explanations for openapi.yml

openapi.yaml
We've decided to refer to this API as GOV.UK Content API and this updates
all references to it to be consistent with this name.
https://trello.com/c/dKWWoydb/1104-consistent-naming-of-govuk-content-api-in-documentation
=> Make naming GOV.UK Content API consistent

openapi.yaml
The concepts described in this documentation are discussed more broadly
in the getting started page of Content API docs.
=> Add documentation links to openapi.yml

app/models/content_item.rb, spec/integration/submitting_content_item_spec.rb, spec/models/content_item_spec.rb
This fixes a situation where routes weren't registered for items that
were once placeholders. When a placeholder was published with a
different format it would not have routes registered as these were the
same as the placeholder - but since the placeholder routes weren't
registered no routes are registered.
=> Fix missing routes from placeholders

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb
This is for grouping documents by core or government. In the short term this will be used in an A/B test to boost core (sometimes referred to as 'mainstream') documents in search results.
https://trello.com/c/z9wtoGTV
=> Add search_user_need_document_supertype

config/mongoid.yml
Need to add the option for connecting to Mongo via SSL in production in order to test this app in the PaaS environment where Mongo is provided externally and can only be accessed over a TLS connection.
=> Add Mongo SSL config.

app/controllers/content_items_controller.rb, app/models/content_item.rb, app/models/route_set.rb, spec/integration/deleting_a_content_item_spec.rb, spec/support/router_helpers.rb
Copied from the last commit:
This change provides a means to delete routes, from the Publishing
API, via the Content Store.
On an architectural level, the Publishing API doesn't directly talk to
the Router API, all communication goes through the Content Store. The
Publishing API can delete content items from the Content Store,
e.g. if you unpublish some content with a vanish type.
This change means that deletions from the Content Store will mean that
the Content Store will delete the relevant routes from the router.
One practical issue which this helps with is removing content/routes
when they are no longer wanted. This is tricky with content with
prefix routes. Say you have two bits of content, A and B where the
routes are:
/A (type prefix)
/A/B
If you wanted to remove B, such that A was …
=> Handle deleting routes when deleting content items

Gemfile, Gemfile.lock, app/models/route_set.rb, spec/integration/deleting_a_content_item_spec.rb, spec/support/router_helpers.rb
Copied from the third commit:
This avoids the Router API service converting these routes to gone
routes, and gets it to actually delete them.
I think this behaviour is better, it avoids state building up in the
Router API and also means that the unpublishing type of vanish will
work, as the routes will be deleted from the router.
=> Hard delete routes

Dockerfile
Dockerfile gets used by the publishing end-to-end tests.  We don't
want the version tested against to be different to the version
in production.
=> Match the Dockerfile ruby image version to .ruby-version

spec/service_consumers/pact_helper.rb
Changing the Content Store to delete routes upon the deletion of the
content means that in the pact tests with the Publishing API, requests
are made to the router-api.
This commit puts in some basic stubs for these requests.
=> Stub some router-api requests in the pact tests

Jenkinsfile
Publishing API publishes a suite of pact tests each time it builds on a
branch and tests these against content-store on the deployed to
production branch. However the inverse of this seems to have been
overlooked and it was possible to merge commits into content-store which
broke these pact tests.
Once https://github.com/alphagov/content-store/pull/333 is merged in this should pass :crossed_fingers:
=> Test against Publishing API pacts as part of build

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb
https://github.com/alphagov/govuk_document_types/pull/33 replaced `user_need_document_supertype` with `content_purpose_document_supertype`. 
This PR makes sure that the content store can handle being sent both by the publishing-api, and makes sure the app returns the new document type. It will fail until https://github.com/alphagov/govuk-content-schemas/pull/678 is deployed.
https://trello.com/c/PBPo5tmL
=> Add the "content purpose" supertype

config/mongoid.yml
This allows us to run the content store in a production like state without requiring multiple Mongo instances to be present.
This is currently utilised as part of running the E2E tests in production.
=> Add ENV var to allow setting Mongo write mode

Gemfile.lock
Github is notifying us that Webrick <= 1.3.1 has a security vulnerability so it seems like a good idea to upgrade it.
=> Update webrick due to security vulnerability

lib/find_by_path.rb, spec/integration/fetching_content_item_spec.rb, spec/lib/find_by_path_spec.rb
This is related to the work in https://github.com/alphagov/content-store/pull/269 but extends this for redirects which were missed and are now a somewhat bizarre inconsistency.
=> Redirect prefix content items for redirect types

app/presenters/content_item_presenter.rb, spec/presenters/content_item_presenter_spec.rb
See: https://github.com/alphagov/gds-api-adapters/pull/805 for context
This is to allow applications other than router the option to know about
which redirects a redirect content item has.
The reason for this is to enable a fallback for the scenario when router
proxies a request to an application but when the application queries the
content store it returns a redirect type which the frontend app has no
option other than return a 500.
=> Include redirects in redirect schema output

config/unicorn.rb
This is now managed via an env var from puppet.
This should be merged once: https://github.com/alphagov/govuk-puppet/pull/7212 is deployed to prod.
=> Remove explicitly setting unicorn worker processes

doc/publish_intents.md
- Publish intents are deleted when a document is published. This was added in https://github.com/alphagov/content-store/pull/297
- Add a link to the housekeeping job which deletes old publish intents
=> Clarify publish intent docs

app/controllers/content_items_controller.rb, spec/integration/submitting_content_item_spec.rb
Log the difference between the scheduled publishing time and the actual publishing time. Use a Statsd `timing` stat, which automatically calculates other stats like the mean and standard deviation.
It might be more useful to calculate some daily aggregates, but at least this will let us start recording some data about publishing delays.
=> Record publishing delays in graphite

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/end_to_end_spec.rb, spec/integration/fetching_content_item_spec.rb
We have added `content_purpose_supergroup` and `content_purpose_subgroup` to govuk-document-types https://github.com/alphagov/govuk_document_types/pull/36. We need to update content-store with this change.
**Note: The tests will fail until https://github.com/alphagov/govuk-content-schemas/pull/722 is deployed.**
=> Add new content purpose supergroup and subgroup

config/schedule.rb, lib/tasks/data_hygiene/publishing_delay_report.rake, lib/tasks/data_hygiene/publishing_delay_reporter.rb, spec/lib/tasks/data_hygiene/publishing_delay_reporter_spec.rb
Add a cron job which runs a rake task every night to send publishing delay stats to graphite.
Calculate the stats directly rather than using a stats gem because the available gems weren't very suitable:
- descriptive-statistics (https://github.com/jtescher/descriptive-statistics) doesn't calculate percentiles in the expected way: it returns nil rather than the maximum value if the percentile requested is larger than the data set, e.g. the 95th percentile of a data set with less than 20 values.
- SciRuby statsample (https://github.com/sciruby/statsample) is too large for what we need: it adds dependencies like a PDF writer and a visualisation toolkit.
=> Report scheduled publishing delays to graphite

app/models/publish_intent.rb
Log a warning when the housekeeping job cleans up any expired publishing intents.
This cleanup job used to be necesssary to delete expired intents, but intents are now deleted when the document is published so there should no longer be any expired intents.
If this doesn't log any warnings in the next few weeks, it should be safe to remove the housekeeping task altogether.
=> Log expired publishing intents to Sentry

app/controllers/content_items_controller.rb, app/models/scheduled_publishing_log_entry.rb, app/presenters/content_item_presenter.rb, spec/factories/scheduled_publishing_log_entry.rb, spec/models/scheduled_publishing_log_entry_spec.rb, spec/presenters/content_item_presenter_spec.rb
Add a new field to the API response for a content item: the most recent scheduled publication date. This will help publishers check whether a scheduled document was published on time by comparing the scheduled time to the actual published time.
The tests for this will fail until alphagov/govuk-content-schemas#724 is merged.
=> Add scheduled publishing time to content item response

app/controllers/content_items_controller.rb, app/models/scheduled_publishing_log_entry.rb, app/presenters/content_item_presenter.rb, spec/factories/scheduled_publishing_log_entry.rb, spec/models/scheduled_publishing_log_entry_spec.rb, spec/presenters/content_item_presenter_spec.rb
This reverts commit cf1747115f9f00e3586c067fe014f6207ca91da5 (PR #391).
This increased the response times by around 50% on staging, so revert this while we consider how to improve this, e.g. by adding an index to ScheduledPublishingLogEntry.
Response times are 150-200 ms on integration, so the extra query didn't make requests noticeably slower.  But on staging, where response times are around 10 ms, the extra query made a significant difference (the red line marks the deployment to staging):
Responses are still fast, but since this is the content-store I'd like to at least investigate adding an index to avoid a 50% increase in response times.
=> Revert "Add scheduled publication time to content item response"

app/controllers/content_items_controller.rb, app/models/scheduled_publishing_log_entry.rb, app/presenters/content_item_presenter.rb, spec/factories/scheduled_publishing_log_entry.rb, spec/models/scheduled_publishing_log_entry_spec.rb, spec/presenters/content_item_presenter_spec.rb
Reapply #391, which was reverted in #394 because of performance problems, and add a Mongo index to speed up the new query.
With the index, request speeds are very similar to before:
The red markers show the three recent deployments:
- the original change (which make requests slower by about 10 ms)
- the revert
- this PR (which increases response times by just 2 or 3 ms)
=> Re-add scheduled publication time to content items

app/models/content_item.rb, spec/integration/end_to_end_spec.rb
This field was removed from govuk_document_types in version 0.2.0: https://github.com/alphagov/govuk_document_types/blob/master/CHANGELOG.md#020
publishing-api is using a later version of this library, so this field is no longer sent to the content-store.
=> Remove unused 'user_need_document_supertype' field

app/controllers/content_items_controller.rb, app/models/publish_intent.rb, spec/integration/submitting_content_item_spec.rb
Publishing intents were sometimes being deleted incorrectly.
They were supposed to be deleted when the final version of the document was published by the whitehall scheduler, but they were sometimes being deleted slightly early when the "coming soon" version of the document was republished - this was triggered by the publishing of the document's attachments. When an attachment is published, dependency resolution in the publishing-api triggers a publishing of all the linked documents, including the parent publication.
Deleting the publishing intent early causes a bug, because the publishing intent is used to set a short cache expiry in the run-up to the scheduled publishing. If the intent is deleted a few minutes early, the "coming soon" version is served to users with the default cache …
=> Fix scheduled publishing delays by not deleting the publishing intent

lib/tasks/data_hygiene/publishing_delay_reporter.rb, spec/lib/tasks/data_hygiene/publishing_delay_reporter_spec.rb
Report statistics and statistics announcements separately to other publication types:
- It's important for national and official statistics to be published on time, so monitor these separately
- Statistics announcements can have incorrect publishing delays. In most cases they are reported correctly, but sometimes they can appear to be published hours or days late because a publisher has linked an announcement to a statistics set _after_ the statistics are published.
=> Group scheduled publishing delay stats by document type

app/controllers/content_items_controller.rb, app/models/content_item.rb, app/models/scheduled_publishing_log_entry.rb, app/presenters/content_item_presenter.rb, spec/factories/scheduled_publishing_log_entry.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/models/content_item_spec.rb, spec/models/scheduled_publishing_log_entry_spec.rb, spec/presenters/content_item_presenter_spec.rb
This is an alternative implementation of #396.
- As suggested in #396, move the `publishing_scheduled_at` field to a database field rather than adding it at query time. This saves the content-store from searching the scheduled publishing log entries on every GET request.
- Add a new `scheduled_publishing_delay_seconds` field to allow publishers to check the delay without having to compare it to the updated time, which may be misleading if the document has been manually published after the scheduled publishing.
cc @cbaines
=> Make publishing time a DB field and add publishing delay

spec/integration/submitting_content_item_spec.rb
I want to avoid more scenarios like the following on CI:
```
1) content item write API with an earlier scheduled publishing log
entry adds the latency to the content item
Failure/Error:
expect(content_item.scheduled_publishing_delay_seconds).to eq(25)
expected: 25
got: 24
(compared using ==)
```
=> Avoid false positives with publishing-api delay seconds

lib/publication_delay_report.rb, lib/tasks/report.rake, spec/lib/publication_delay_report_spec.rb
This report shows content items with a delay in the scheduled publication for the last week. It outputs its results as a CSV file to standard output. The plan is for this to be automatically sent to various people every week.
[Trello Card](https://trello.com/c/rkOiRFUV/128-run-the-statistics-publication-delay-report-weekly-and-send-it-to-alice-2)
=> Add a scheduled publication delay report

app/models/content_item.rb, spec/models/content_item_spec.rb
Trello: https://trello.com/c/eFxqPwNP/115-more-diagnostic-information-to-diagnose-404-scheduled-publishing-problems-2
This is to provide more visibility about when they are actually created
which can help with determining the point a route was active on GOV.UK
and be useful in debugging situations where it would previously 404 and
it was not known why.
=> Set created_at timestamps on Content Items

config/mongoid.yml
Removed in https://github.com/alphagov/content-store/commit/e7383e24e4dd6a733f04538659ac379c9151e523
The default read mode for mongodb is primary:
_By default, an application directs its read operations to the primary member in a replica set._
However in a scenario where the primary fails we should be able to read from the secondaries until the primary is healthy.
This would allow frontend applications to respond with albeit slightly stale data rather than 500s.
Further reading:
https://docs.mongodb.com/manual/core/read-preference/
Slightly related to https://trello.com/c/cF8wkUuJ/174-investigate-mongo-replication-on-staging-failing-every-morning
DNM because we should test this config on integration first.
=> Re-apply 'primary preferred' read mode

app/models/content_item.rb, app/presenters/content_item_presenter.rb, doc/content_item_fields.md, doc/input_examples/frontend-app/quick_answer.json, doc/input_examples/generic.json, doc/output_examples/generic.json, openapi.yaml, spec/integration/fetching_content_item_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/integration/submitting_placeholder_item_spec.rb, spec/integration/submitting_redirect_item_spec.rb
The use of this field has been replaced with the `meets_user_needs`
link type.
=> Remove all the code related to need_ids

Jenkinsfile, lib/route_consistency_checker.rb
In order to turn brakeman on we need to either fix the brakeman warnings or include an ignore file for the warnings we deem safe. I've chosen to fix the warnings in this instance because I think the code change is preferable to introducing a `brakeman.ignore` file.
The current implementation of `RouteConsistencyChecker` relies on string interpolation for a `WHERE` clause as follows:
```
def find_content_item_for_field(path, kind)
ContentItem.where("#{kind}s.path" => path).entries
...
```
Only two methods call `find_content_item_for_field` and both of these send an explicit string that has not come from outside the class itself (one sends the string `route` and the other `redirect`). This method, as it stands, with the code that calls it, is safe.
Refactoring the code makes it slightly …
=> Turn brakeman on

app/models/publish_intent.rb, config/schedule.rb, lib/tasks/housekeeping.rake, spec/models/publish_intent_spec.rb
Publishing intents are automatically deleted now as soon as the content item is published.
In https://github.com/alphagov/content-store/pull/392 we added a Sentry alert to tell us if this task actually does anything. The error has never appeared in Sentry so it's fine to remove this task.
[Trello Card](https://trello.com/c/1M1JNno5/158-review-and-remove-content-store-housekeeping-task)
=> Remove housekeeping task which clears publishing intents

config/mongoid.yml
This will spread the read requests across the secondary Mongo instances
automatically and spare the primary from taking all the load as is
happening currently. This should obviate the need to increase the sizes
of the Mongo instances and should also improve performance.
=> Set Mongo client to prefer reads from secondaries

app/models/content_item.rb, app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb
We're no longer using supertypes embedded in content items and search indices, because changing anything requires republishing of all the affected content. This makes sure that we don't expose the supertypes in the content item.
The data still is persisted in the database, we'll need to remove the supertypes from the publishing-api first.
This will make https://github.com/alphagov/govuk-content-schemas/pull/852 pass.
https://trello.com/c/hp5BJD2i
=> Don't expose supertypes in content items

lib/find_gsi_domain_references.rb, lib/tasks/report.rake
The government is migrating away from GSI domains by March 2019.
This script searches for all references to gsi-family domains (gsi/gse/gcsx/gsx) and outputs them to a CSV file.
This output can be used to automatically or manually change the references from the relevant publishing apps.
Built on top of work by @deborahchua 
Trello: https://trello.com/c/jfpoEh55/698-next-steps-on-changing-gsigovuk-domains-to-non-gsigovuk-in-static-and-dynamic-content-on-govuk
Sample console output:
```
vagrant@development:/var/govuk/content-store$ bundle exec rake report:find_gsi_domain_references
Searching for gsi.gov.uk...
Found 11458 items containing gsi.gov.uk
Searching for gse.gov.uk...
Found 17 items containing gse.gov.uk
Searching for gcsx.gov.uk...
Found 12 items containing gcsx.gov.uk
Searching …
```
=> Find gsi-family domain references in content

lib/find_gsi_domain_references.rb
This commit adds some new fields to the script that looks for GSI-family email addresses, and fixes the `details.body` matcher.
=> Add more fields to the GSI finding script

lib/find_gsi_domain_references.rb
This commit adds checks for both the `details.body` and `details.body.content` hashes when looking for GSI-family email addresses.
=> Check both body and content for GSI email addresses

lib/find_gsi_domain_references.rb
This commit checks the `content` hash for the `details.introductory_paragraph` and `details.more_information` fields when search for GSI-family email addresses.
=> Check content hash for more fields for GSI email addresses

app/models/content_item.rb, lib/tasks/routes.rake
In the unlikely event that registering routes with the router failed but the content-store believes that it succeeded, it will refuse to send the routes again even if the document is represented. This is because it caches the routes from the previous item and compares.
These Rake tasks bypass these checks allowing routes to be registered with the router.
[Trello Card](https://trello.com/c/gnK6FhQb/828-gather-current-convenience-scripts-rake-tasks-that-might-help-during-brexit-publishing)
=> Add Rake tasks for registering routes

README.md
As a new joiner, it's quite hard to find all of the different aspects of the
content store in one place. This is an attempt to touch upon all of the key
parts, from reading & writing to the content store, to dealing with different
content types by use of schemas.
Depended on by https://github.com/alphagov/govuk-developer-docs/pull/1810.
=> Describe content & publishing API and schemas

config/mongoid.yml
We currently have to override `mongoid.yml` in govuk-docker, because the test database URL is hard coded.
=> Allow test database to be specified with ENV

Gemfile, Gemfile.lock
This was added in 9b2a2bd4d417da2a6a6f0976f9b4f28bb4060696 and the task was removed in 1e0efdfc9b3f26ffcedf0611ce7a1164302ef3db but the dependency was left in.
Alternative to #591.
=> Remove hashdiff

app/controllers/content_items_controller.rb, app/models/content_item.rb, spec/factories/content_item.rb, spec/integration/access_limited_spec.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/public_api_request_spec.rb, spec/models/content_item_spec.rb
This PR adds support for allowing users to see content restricted to organisations.
It compares the `X-Govuk-Authenticated-User-Organisation` header sent in the request to the organisations listed within the access limiting properties.
=> Support access limiting by user organisation

lib/tasks/pact.rake
This resolves an issue where pact tests run multiple times for a
particular changes for reasons that may have been lost to history.
This updates the configuration to be consistent with Publishing API as
per: https://github.com/alphagov/publishing-api/pull/1555
=> Update pact configuration for less test runs

config/initializers/cookies_serializer.rb
To avoid any remote code execution issues with the marshal
serializer. Not that they'll affect the content store, and internal
application that to my knowledge doesn't use cookies... ¯\_(ツ)_/¯
=> Switch the cookie serializer to json

spec/service_consumers/pact_helper.rb
This makes the default `rake pact:verify` consistent with the default
pact the Jenkins job runs.
=> Default to running pacts against production Publishing API

lib/tasks/pact.rake
In b30c1ff I accidentally caused a regression of the change made in
56f5c14 for the special case of the master branch. This retains the
consistent branch behaviour.
=> Fix regressing special pact case

config/mongoid.yml
The Content Store is a read heavy application, as it only processes
writes when things change, but it's constantly serving the frontend
applications with data.
This can be seen in the load on the MongoDB machines, currently the
primary gets off lightly with a low load, and the secondary machines
handle most of the operations.
Using the nearest MongoDB machine should spread the load more evenly,
and might even increase performance due to reduced network latency.
I've been looking at this, as the MongoDB machines often complain
about high load (especially on the AWS side of Staging).
=> Use the `nearest` read mode for MongoDB

README.md
* Fix broken link to govuk-content-schemas repo.
* Make the relative links to the Content Store docs (Technical Information page) and LICENSE file absolute so that they work when included from https://docs.publishing.service.gov.uk/apis/content-store.html
=> Fix two broken links in docs

app/presenters/expanded_links_presenter.rb, spec/presenters/expanded_links_presenter_spec.rb
This is private information and should not be shown when accessing
the content store - it is just for internal content store processing.
I've created a 'secret_fields' method which returns a hash, so that
we can easily add more secret fields in future if necessary.
Trello: https://trello.com/c/DR4BMQzv/134-dont-show-authbypassids-in-content-stores-expanded-links
=> Hide 'auth_bypass_ids' field from link expansion

app/models/content_item.rb, spec/models/content_item_spec.rb
Trello: https://trello.com/c/AhyYCLZy/142-separate-authbypassids-from-access-limiting-in-content-store
This creates a new field that is intended to be the destination of data
that is transitioned from the access_limited object. The reason data is
being moved out of the access_limited field is that it creates confusion
given that auth_bypass doesn't do access limiting - quite the opposite
in fact.
To start with this transition this creates a field on ContentItem that
is written to each time data is saved which will be a replica of the
data in access_limited.
=> Create auth_bypass_ids field

db/migrate/20191010094643_backfill_auth_bypass_ids.rb
Trello: https://trello.com/c/AhyYCLZy/142-separate-authbypassids-from-access-limiting-in-content-store
This depends on https://github.com/alphagov/content-store/pull/630 being deployed to production and builds on it.
This loops through content items to set each of them with an
auth_bypass_ids field if they have an access_limited object.
=> Backfill auth bypass ids

app/models/content_item.rb, spec/factories/content_item.rb, spec/integration/access_limited_spec.rb, spec/models/content_item_spec.rb
Part of: Trello: https://trello.com/c/AhyYCLZy
Follows on from: PRs #630 and #631 
Related to:  PR #636 
Switch the code to use the new auth_bypass_ids field and no longer check or populate the old field
Uses the new auth_bypass_ids, and no longer populates it from the auth_bypass_ids in the access_limited field.
=> Use new auth bypass ids field

db/migrate/20191011142024_remove_auth_by_pass_i_ds_from_access_limited.rb
Part of: Trello: https://trello.com/c/AhyYCLZy
Related to: PRs #634 
Follows on from: PRs #630 and #631
Migrates the existing `auth_bypass_ids` from the `access_limited` attribute to the new `auth_bypass_ids` field.
`auth_bypass_ids` are being decoupled from access limiting, and will instead be stored in a separate field. This ensures that we don't lose the existing `auth_bypass_ids` and cause users that don't have a signon accounts to lose access to the individual content items they have been given access to.
=> Migrate existing auth_bypass_ids from access_limited attribute to new field

app/models/content_item.rb, spec/models/content_item_spec.rb
Follows on from: https://github.com/alphagov/publishing-api/pull/1629
Reverts: https://github.com/alphagov/content-store/commit/5910091d012468a21a27dae21536241e7e2037fe#diff-7a1fc60457a3430a2bd0c87f52941d6a
Now that publishing-api is no longer sending auth_bypass_ids in the access_limited hash,
we no longer need to check for it.
=> Remove transition code

app/presenters/content_item_presenter.rb, spec/presenters/content_item_presenter_spec.rb
Currently we resolve text/html content in the description and in the details hash, but not in the links.
This leads to some inconsistency content items, specifically people where the links to roles include the different content types but the content item for the role itself does not. This also makes it harder to write "dumb" frontend apps as they need to be aware on the different content types and perform the resolving in the frontend app.
Example:
```json
{
"api_path": "/api/content/government/ministers/prime-minister",
"base_path": "/government/ministers/prime-minister",
"content_id": "845e5811-c0f1-11e4-8223-005056011aef",
"document_type": "ministerial_role",
"locale": "en",
"public_updated_at": "2018-11-05T08:52:39Z",
"schema_name": "role",
"title": "Prime Minister",
"withdrawn": …
```
=> Resolve text/html content in links

app/models/content_item.rb, spec/presenters/content_item_presenter_spec.rb
This is one step towards solving #632 and avoids unnecessary confusion over their being two fields for accessing the links.
There are only 310 content items left which have something in the `links`:
```rb
irb(main):005:0> ContentItem.where(:links.nin => [{}, nil]).count
=> 310
```
I don't think we need to write a migration to remove this field because as new content is presented to the content store, it'll get overwritten anyway.
=> Remove links field

db/migrate/20141219114603_remove_non_case_study_whitehall_unpublishings.rb, db/migrate/20150220114658_really_remove_non_case_study_whitehall_unpublishings.rb, db/migrate/20151013123045_make_inconsistent_policies_into_redirects.rb, db/migrate/20151014135153_add_redirects_for_raib.rb, db/migrate/20151015100245_redirect_publications_to_statistics.rb, db/migrate/20151015103826_fix_redirects_for_schools_commissioner.rb, db/migrate/20151015111051_fix404ing_content_items.rb, db/migrate/20151020130422_set_redirects_for_odd_unpublishings.rb, db/migrate/20170822104138_remove_obselete_content_items_index.rb
When we tried to deploy content store in a new environment, with a fresh mongodb, these migrations failed.
This adds fixes for the various failures so we can run migrations against a new empty mongodb.
=> Enable migrations to run against a new, empty cluster

.github/dependabot.yml
The dependencies named in the code in this commit have non-standard
names and we are not encouraging further creation of `gds-*` named
dependencies. Therefore we have taken the decision to name these
dependencies explicitly. Read the [discussion] in #750.
Trello: https://trello.com/c/uPoriyfJ/2049-add-dependabot-configuration-to-each-repo-blitz-pair
[discussion]: https://github.com/alphagov/content-store/pull/750#discussion_r454208436
=> Explicitly name gds-* dependencies

lib/find_by_path.rb
This makes a couple of changes to the FindByPath module to try improve its performance. Firstly it only checks redirects if there are any, this allows PublishIntent to make it's queries by index scans rather than collection scans. Secondly it splits the work into two queries, the first being a simple find by id and only if that fails doing the query to check the routes/redirects.
I'm going to run this on integration/staging for a bit to try determine if it has an impact.
In integration:
In staging:
It seems that this makes a noticeable impact on PublishIntent, yet only a negligible impact on ContentItem look ups. It also doesn't seem to fully remove spikes as this later graph showed:
So this may well help the situations that have caused problems, but it looks like it won't fully resolve …
=> Make find_by_path more efficient

spec/integration/submitting_content_item_spec.rb
In 1ffd624f I applied a fix to this test however this didn't appear to
be sufficient to root out the flakiness as I failed to notice that this
test relied on non-deterministic ordering. Attempting locally I didn't
manage to replicate the failure however I've seen it in Jenkins with:
```
1) content item write API creating a new content item with an earlier scheduled publishing logs the publishing delays for each scheduled publishing
Failure/Error: expect(log_entries[0].scheduled_publication_time).to eq(first_scheduled_time)
expected: 2020-08-31 12:00:00.000000000 +0000
got: Tue, 01 Sep 2020 12:00:00.000000000 +0000
(compared using ==)
Diff:
@@ -1 +1 @@
-Mon, 31 Aug 2020 12:00:00 UTC +00:00
+Tue, 01 Sep 2020 12:00:00 +0000
```
Thus applying an ordering to this query should make the ordering …
=> Apply deterministic ordering to flakey test

app/models/content_item.rb
https://sentry.io/organizations/govuk/issues/1676038415/?project=202242
Previously we could not know the cause of a communication issue
between this app and the Router, since we hard-coded the error
message. This changes the message to include the actual error.
=> Show actual error from Router

app/lib/publication_delay_report.rb
This PR contains the changes necessary for the app to run on Ruby 2.7.1.
The version of Ruby is left the same, since there is a script that can be run after all the apps have been updated to update the version all at once
Tested locally with ruby 2.7.1 and 2.6.6
CSV deprecation warnings see 6323f51
Also deprecation warning which might need updating at the gem source:
```
ruby-2.7.1/gems/mongoid-7.1.2/lib/mongoid/errors/mongoid_error.rb:51: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby-2.7.1/gems/i18n-1.8.5/lib/i18n.rb:195: warning: The called method `translate' is defined here
```
=> Update to ruby 2.7.1

config/application.rb
This adds the iso code gu and pa for supporting translations in those languages.
=> Add locales for Gujarati and Punjabi

config/routes.rb, spec/integration/healthcheck_spec.rb
https://trello.com/c/36cdHP3z/620-improve-the-content-store-healthcheck-to-check-mongo-so-failing-instances-are-automatically-removed-from-the-lb
This more accurately reflects whether an instance of the app is able
to serve requests, which contributed to an incident [1].
[1]: https://docs.google.com/document/d/1q0dmaRaK1pnoKK_EGikdstUOtBEiaCaswMYS9ITFbL0/edit#
=> Do a real /healthcheck for MongoDB connectivity

spec/factories/user.rb
This should avoid an [error we're seeing on CI builds](https://ci.integration.publishing.service.gov.uk/job/content-store/job/master/1064/console):
```
An error occurred in a `before(:suite)` hook.
Failure/Error: FactoryBot.lint
FactoryBot::InvalidFactoryError:
The following factories are invalid:
* user - insertDocument :: caused by :: 11000 E11000 duplicate key error index: content_store_test.users.$uid_1  dup key: { : null } (11000) (on ip-10-1-4-148:27017, legacy retry, attempt 1) (Mongo::Error::OperationFailure)
```
It follows a similar pattern found [in Whitehall](https://github.com/alphagov/whitehall/blob/bf7cf0566a69a040e426e1ac5fa7245982ac46a9/test/factories/users.rb#L10-L12) and [in Content Publisher](https://github.com/alphagov/content-publisher/blob/3cdda97cd3f3acdb11f2d8adf175 …
=> Add explicit uid to user factory

config/application.rb
We already support `pa`, Punjabi Gurmukhi, a language used in Punjab,
India. This is to add `pa-ur`, Punjabi Shahmukhi, a language used in
Punjab, Pakistan, that uses the Urdu script.
More information on the two languages can be found on this Wikipedia
page: https://en.wikipedia.org/wiki/Punjabi_language
The reason `pa-ur` was chosen as locale code is that `pa` is the
language code for Punjabi and `ur` is the script subtag for Urdu. More
information on this can be found on this Mozilla developer docs page:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#Language_tag_syntax
Docs followed: https://docs.publishing.service.gov.uk/manual/add-translation-whitehall.html
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/4371686
Related PRs:
- …
=> Add pa-ur locale (Punjabi Shahmukhi - Urdu script)

app/models/content_item.rb, spec/integration/submitting_content_item_spec.rb
Trello: https://trello.com/c/cRI17wof/981-investigate-content-store-returning-5xx-errors-when-router-registration-fails
Previously we were treating communication with Router API as a client
error and returning a 422 response to the Publishing API when there was
a Router problem. This is a bit misleading as it is not the case that
updating the client request can resolve the error.
By instead raising an exception these errors will be converted into a
500 response by Rails. This will help us, in the event of more Router
API problems, distinguish server errors from client errors.
=> Re-raise Router API expectations to ensure 5xx responses

Procfile
Looking at the commit where this was added (d11e9e9cbb97a7ec9729d637535d6b4e2fc96950),
the port number should actually have been `3068` to match the
value in the (then) startup.sh file and the (now) Dockerfile:
https://github.com/alphagov/content-store/blame/bbd42092fce84754c084f0c496240ec0741df34e/Dockerfile#L8
`3086` seems to be being used by the Transition app:
https://github.com/search?q=org%3Aalphagov+3086&type=code
This was set 3 years ago, however, so begs the question: what has
the impact of this been and why have we not noticed?
=> Correct port number

config/mongoid.yml
We are seeing content-store read requests time out.
This change to the read prefence [1] is intended to
see if we can reduce reads to the primary, which seems
to have a higher percentage rate of locks.
[1] https://docs.mongodb.com/v2.6/core/read-preference/
=> Switch read mode to secondaryPreferred

docs/access-limited-content-items.md
It has not always been clear in the past that we can change our
organisation in Signon to get around the access limited feature.
https://trello.com/c/TkHxV4Op/1190-add-docs-on-viewing-access-limited-content-items
=> Add docs for 2nd line on access limited documents

config/application.rb
Partially implements GOV.UK RFC 144. We will gradually reduce the TTL to 5 minutes, once we're more confident on the impact on performance. The next step will be to audit frontend applications to ensure that this TTL is honoured.
To be merged once https://github.com/alphagov/govuk-rfcs/pull/144 is approved.
=> Reduce default TTL for GOV.UK pages to 20 minutes

config/application.rb
This changes the default value of this configuration option to match how
it is configured in govuk-puppet for all environments [1].
This has been applied to reduce confusion where it looks like this code
is set to quite a deliberate value, whereas it was one that represented
an in between state in a migration.
[1]: https://github.com/alphagov/govuk-puppet/pull/11538
=> Update default cache TTL to 5 minutes

app/controllers/application_controller.rb, spec/integration/fetching_content_item_spec.rb, spec/integration/submitting_content_item_spec.rb
We occasionally are subject to malicious users trying to discover
weaknesses in our application by sending invalid URIs.
This change updates our handling so that we return a 400 Bad Request
response, rather than recording this as an application error.
I debated about whether to return a 400 (Bad Request) response or a 406
(Not Acceptable) response. However I noticed we already had precedence
for 400 for invalid JSON so I kept consistent with that.
Before:
After:
=> Handle errors for bad URI requests

app/lib/find_specific_term.rb, lib/tasks/report.rake
This reverts commit 8b3b6883532e108892af45443fbe037eac689edb.
Originaly removed as part of code cleanup for CD work, didn't realise
this was in fact still in use by the content community.
Expected to be replaced by the Data Products Govgraph soon anyway.
=> Revert "Remove find_specific_term task"

app/lib/find_specific_term.rb, spec/lib/find_specific_term_spec.rb
This task was added back in after being removed during CD work, didn't realise it was still in use by the content community. So to make content-store compliant with test coverage for CD it needs to be tested adequately.
Trello: https://trello.com/c/aDiHro0u/26-enable-continuous-deployment-for-content-store
=> New test for the find specific term rake task

Gemfile.lock
Reverts alphagov/content-store#987
We are currently filling our log files with deprecation warnings for `Plek.current`, which is causing the machines to run out of disk space:
```
Plek.current is deprecated and will be removed. Use Plek.new or Plek.find instead.
```
Reverting until we replace all uses of this.
=> Revert "Bump plek from 4.0.0 to 4.1.0"

Gemfile.lock, app/presenters/expanded_links_presenter.rb, config/application.rb, spec/presenters/expanded_links_presenter_spec.rb
Usage of `Plek.current` was marked as deprecated in https://github.com/alphagov/plek/pull/94, therefore we should remove uses of the old syntax before upgrading Plek, else we'll log lots of deprecation warnings.
This resolves the issue that caused us to revert Plek from `4.1.0` to `4.0.0` in https://github.com/alphagov/content-store/pull/989.
=> Replace Plek.current with Plek.new

app/lib/find_specific_term.rb, lib/tasks/report.rake, spec/lib/find_specific_term_spec.rb
Adds a task to find content that doesn't match a particular format. 
Usage:
```
bundle exec rake report:find_specific_term_references_excluding_types[Term,"doc_type_1 doc_type_2"]
```
e.g.
```
bundle exec rake report:find_specific_term_references_excluding_types[Licence,"licence aaib_report"]
```
Content items aren't always created using the expected format.
=> Add task to exclude terms that match document type

app/models/route_set.rb, spec/models/route_set_spec.rb
Content Store currently updates the backend address in Router every time a content item or publishing intent is saved. This was originally done [to simplify a long-since-completed migration](https://github.com/alphagov/content-store/pull/23), but it's now both unnecessary and causes problems with parallel running for Replatforming, where the backend addresses necessarily differ between the old and new installations.
This lets us disable this esoteric behaviour on the Kubernetes side during the Replatforming pilot phase.
Tested: verified that router_api.add_backend is called when the NO_SET_ROUTER_BACKEND_ADDRESS_ON_PUBLISH env var is not set and not otherwise.
=> Add a feature flag to disable modifying Router backends on the fly.

app/controllers/content_items_controller.rb, spec/integration/fetching_content_item_spec.rb
This addresses https://github.com/alphagov/content-store/issues/1006
This sets a `Access-Control-Allow-Origin: *` header on HTTP responses to the show endpoint, this will allow requests to this API to originate (via JS) from hosts other than www.gov.uk.
The reason for adding this is resolve the issue raised on GitHub 1006 [1]. GOV.UK doesn't directly need this as it doesn't make use of client side requests to the Content Store and, if it did, they'd be from the same host. However this is added in to reflect that this is indeed a partially supported public API [2] and that we are not concerned with JS clients calling it from a different host.
I only put this on the one endpoint as there didn't seem to be any need to have it on endpoints other than ContentItems#show. I also didn't implement …
=> Allow cross-origin requests to access public content endpoint

.github/workflows/ci.yml, .github/workflows/verify-pact.yml
This adds a reuseable workflow to run Pact tests. This workflow is called during CI and also CI for Publishing API.
=> Add Pact tests

config/initializers/content_security_policy.rb
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
This comment has been done to explain to future people why this app doesn't need one.
This CSP was added as part of a round of Rails upgrades [1] on GOV.UK apps which was applied quite uniformly, so the context of this app being API only wasn't considered.
[1]: https://github.com/alphagov/content-store/pull/746
=> Replace CSP with a comment explaining why we don't have one

.github/workflows/ci.yml, .github/workflows/verify-pact.yml
This provides an alternative method for this workflow to execute
Publishing API pact tests. Rather than accessing the Pact tests via the
internet, downloading them from the pact-broker, this instead allows an
input of an artifact filename. This action will download that artifact
and run against the pacts.
The motivation for this approach is that it can allow the Publishing API
CI [1] to execute these tests without the initiator of a Publishing API
needing access to write to the GOV.UK Pact Broker. This is a problem we
are currently experiencing with Dependabot as it does not have access to
GitHub Action secrets.
At the moment, and likely for the forseeable future, there isn't a
scenario where we'd need to use any file other than
`publishing_api-content_store.json` so I've hardcoded this. …
=> Allow verify-pact workflow to accept an artifact input

Procfile, config/unicorn.rb
https://github.com/alphagov/content-store/pull/1063 updated govuk-app-config and the dependency on unicorn so these can be removed
=> Remove unicorn related things

doc/adr/0001-port-content-store-to-postgresql-on-rds.md
Following the approval of [GOV.UK RFC-158](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-158-port-content-store-to-postgresql.md), this ADR records the decision to proceed. 
[Trello card](https://trello.com/c/9p5dQf3r/598-make-an-architectural-decision-record-for-rfc158-content-store-postgresql) and [Rendered version](https://github.com/alphagov/content-store/blob/add-adr-for-porting-to-postgresql/doc/adr/0001-port-content-store-to-postgresql-on-rds.md)
Follow [these …
=> Add ADR-0001: Port Content Store to PostgreSQL on RDS

app/lib/mock_router_api.rb, app/models/route_set.rb, config/application.rb, lib/tasks/register_backends.rake, spec/config/application_config_spec.rb, spec/lib/mock_router_api_spec.rb, spec/models/route_set_spec.rb
Allows [router-api](https://github.com/alphagov/router-api) calls to be disabled by setting this environment variable. 
This then allows us to avoid the potential for conflicts when we deploy both the Mongo and [PostgreSQL](https://github.com/alphagov/content-store-on-postgresql) versions simultaneously behind a [mirroring proxy](https://github.com/alphagov/content-store-proxy), during the migration of content-store from Mongo to PostgreSQL. In this scenario, only the primary will update routes in Router API, and the secondary will not.
[Trello card](https://trello.com/c/pgBHpAZ7/616-put-all-router-api-updates-behind-a-feature-flag-in-content-store) / [Overall Epic](https://trello.com/c/C1BQDFTG/502-plan-for-migrating-content-store-off-mongodb)
This application is owned by the publishing …
=> Mock out router-api calls when DISABLE_ROUTER_API is true

app/models/route_set.rb, spec/models/route_set_spec.rb, spec/support/router_helpers.rb
This flag was [added for the transition to Kubernetes](https://github.com/alphagov/content-store/pull/1015). It's no longer needed. Remove the flag here so that we can remove it from the config once this lands.
Also remove some references to "commit" in test names (router-api no longer has a "commit" operation).
=> Clean up NO_SET_ROUTER_BACKEND_ADDRESS_ON_PUBLISH flag.

Gemfile.lock, app/models/route_set.rb, lib/tasks/register_backends.rake, spec/integration/deleting_a_content_item_spec.rb, spec/integration/submitting_content_item_spec.rb, spec/support/router_helpers.rb
No functional change. See https://github.com/alphagov/router-api/pull/550.
Depends on https://github.com/alphagov/gds-api-adapters/pull/1196 and #1077.
=> Update to gds-api-adaptors 88 + fix up test helpers.

Dockerfile
On merging #1088, the subsequent [container build step failed](https://github.com/alphagov/content-store/actions/runs/5277850735/jobs/9546404952). On investigation, there were a few issues - `wget` is not actually installed on the base image, the package/repo references were the wrong way round, the package was a .tgz not a .deb, etc. 
This PR fixes the build by:
- replacing wget with `curl`
- downloading the `.deb` package instead of the `.tgz` 
- adding the all-important './' to the apt-get install cmd 
I've tested the image can now be built locally with `docker build .` (I should have tested the build on the branch locally before merging rather than leaving it to CI, my bad) 
This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform …
=> Fix the container build which broke in #9d32811

lib/tasks/export.rake
The `export_all` rake task added in #1088 had a problem with the `path:` argument, leading to an error when run via Kubernetes CronJob:
```
NameError: undefined local variable or method `path' for main:Object
MongoExporter.export_all(path:)
```
This PR fixes the error, and has been tested from a shell on the content-store-app container
[Trello card](https://trello.com/c/GMoOthyj/671-add-step-to-overnight-environment-sync-job-to-export-mongodb-to-json-and-import-to-postgresql)
This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform when you raise any PRs.
Follow …
=> fix passing of path arg to MongoExporter in rake task

app/lib/json_importer.rb, app/models/content_item.rb, db/migrate/20230623082107_allow_null_timestamps.rb, db/migrate/20230623112332_allow_null_timestamps_on_scheduled_pub_and_pub_intents.rb, db/schema.rb, spec/lib/json_importer_spec.rb
When we compare the JSON generated by this PostgreSQL branch side-by-side against the same data in the original MongoDB content-store, we find a few inconsistencies:
- the  `created_at`/`updated_at` timestamps were null in many of the MongoDB records, yet in the import process the `null` `created_at` on the PostgreSQL side had been defaulted to `Time.now` 
- the Mongo `_id` field was appearing in the generated JSON on the PostgreSQL side
- the UTC timezone was represented differently for top-level timestamps  ("+00:00" vs "Z")
This PR fixes the first two issues, a separate PR (#1094) against the `main` branch addresses the third. 
⚠️ This repo is …
=> Fix inconsistencies with Mongo JSON

Gemfile, Gemfile.lock, app/lib/hash_sorter.rb, app/presenters/content_item_presenter.rb, app/presenters/expanded_links_presenter.rb, spec/lib/hash_sorter_spec.rb
... for equivalence with `port-to-postgres` version
When dual-running content-store on MongoDB (main) and PostgreSQL (port-to-postgresql branch), we find that [the JSON generated by the two versions differs](https://trello.com/c/1gljPBwl/720-find-out-why-the-contentitem-links-field-differs-between-mongo-pg). After much investigation, it seems that the remaining source of difference is the order of keys in the content_items - particularly in the `links` JSON.
The source of this difference is that Mongo stores the data as BSON, which [preserves the order of the JSON it is given](https://softwareengineering.stackexchange.com/a/340269](https://softwareengineering.stackexchange.com/a/340269) ):
> A BSON data structure is an ordered object, not a dictionary  
whereas in PostgreSQL we store the …
=> Present content-item JSON with deep-sorted keys

Gemfile, Gemfile.lock, app/lib/hash_sorter.rb, app/presenters/content_item_presenter.rb, app/presenters/expanded_links_presenter.rb, spec/lib/hash_sorter_spec.rb, spec/presenters/content_item_presenter_spec.rb, spec/presenters/expanded_links_presenter_spec.rb
This is an updated version of PR #1096, having isolated the cause of the problem described in #1097 (`.deep_symbolize_keys` called at the wrong level) and added a test case to catch the issue in #1099, plus explicit tests that the sorting behaviour is correct.
Trello cards [1](https://trello.com/c/1gljPBwl/720-find-out-why-the-contentitem-links-field-differs-between-mongo-pg) and [2](https://trello.com/c/nRO5J6HW/726-re-introduce-the-hash-sorting-in-content-store-but-this-time-without-breaking-the-frontends)
I've [deployed this to integration](https://github.com/alphagov/content-store/actions/runs/5411392314) and tested that :
a) this does not drop the `role_appointments[*] -> links` (as was found in #1096) :
Before on the left, after on the right. Also note the hashes on the right are …
=> Reintroduce hash sorting for expanded content-item and links

.github/workflows/deploy.yml
Allows us to build the port-to-postgresql branch to a differently-named container in ECR (`content-store-postgresql-branch`) 
as part of [dual-running both versions behind a proxy on integration](https://trello.com/c/BIQ9GmY5/601-deploy-content-store-proxy-and-content-store-on-postgresql-in-integration-for-the-draft-content-store)
=> Add choice of ECR repository name on build-and-publish-image

.github/workflows/deploy.yml
I didn't spot this in #1086. GitHub really ought to syntax-check these automatically pre-merge.
=> Fix syntax error in deploy.yml workflow.

app/presenters/content_item_presenter.rb, spec/integration/fetching_content_item_spec.rb, spec/presenters/content_item_presenter_spec.rb
This is the standard format for timestamps, and also has the benefit of eliminating almost all millisecond-differences between updated_at timestamps while dual-running PostgreSQL & MongoDB versions ([Trello card](https://trello.com/c/N97rWb93/738-make-content-store-contentitempresenter-render-updatedat-with-just-single-second-precision-rather-than-millisecond-precision))
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
=> Render all content_item timestamps in JSON as ISO8601 format. 

.github/workflows/deploy.yml
Commit 5c9e9f6af13a18e17e8cf7d7cdd8bd3d6e5bb2c1 added a choice of ECR repository name on build-and-publish-image.
One might think that the default value of the input is there to provide a fallback for non-workflow_dispatch triggered jobs.
One might, apparently, be wrong[1].
Automatic deploys on content-store have been failing since the choice was introduced, while manual deploys are succeeding. The error is that the image tag is invalid, and it is invalid because it is missing the value of `ECR_REPOSITORY`.
Thanks to Bruce for identifying the related commits, which provided me with a clue of where to look for answers!
[1] https://dev.to/mrmike/github-action-handling-input-default-value-5f2g
This application is owned by the publishing platform team. Please let us know in …
=> Provide fallback value for ecrRepositoryName

.gitignore, app/lib/json_importer.rb, spec/lib/json_importer_spec.rb
Restore offline-table JSON import functionality to the `port-to-postgresql` branch, lost after rebase-gone-wrong.
This should hopefully fix the overnight mongo-to-postgresql ETL job.
=> Restore offline table import

app/models/content_item.rb, spec/models/content_item_spec.rb
The existing code wraps all given `description` values in a hash, even when given a description that is already a Hash.
We got away with this on Mongo because of the different way setters & getters are overridden between Mongoid & ActiveRecord, but on PostgreSQL we need to detect & handle this case explicitly.
This issue was originally fixed on the `port-to-postgresql` branch around 10th July, but appears to have been lost in the giant rebase-gone-wrong. This PR re-fixes the issue. 
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
=> (re-)fix issue that causes doubly-nested description Hashes on PostgreSQL

lib/tasks/temp_cleanup_whitehall_frontend.rake
All public rendering has been removed from Whitehall, therefore no content items should exist that believe they should be rendered by Whitehall Frontend.
A mismatch currently occurs where router believes these items of content should be redirected, but Content Store has a content item for them (e.g. policy areas).
Presumably a temporary rake task or something on a console was run at some distant point in the past to implement the redirects in router, but the content items were never removed.
Three issues were caused:
- users can access the content items still, even though the content has been changed/withdrawn/moved
- running the `register:routes` rake task in Content Store will result in `whitehall-frontend` being registered with router, even though it no longer exists
- it's causing us …
=> Add temporary rake task to cleanup Whitehall Frontend documents

lib/tasks/temp_cleanup_whitehall_frontend.rake
This task has now been run in production, so can be deleted.
Reverts alphagov/content-store#1128
[Trello card](https://trello.com/c/2wA7AA8J)
=> Revert "Add temporary rake task to cleanup Whitehall Frontend documents"

app/controllers/application_controller.rb
..to try and debug a problem with updates only getting as far as publishing-api ([Trello card](https://trello.com/c/LTCo5fnV/802-travel-advice-alert-status-not-updating))
=> Add more explicit & verbose logging when the app sends a HTTP 400

app/models/content_item.rb, spec/models/content_item_spec.rb
This fixes a bug where unpublished redirects in short URL manager aren't removed from the content store (so continue to work on the website).
Users of the content-store API (i.e. publishing-api) might make API calls with values they want to reset provided as `nil`. For example, if you wanted to clear some redirects on a content item, you might do something like:
```
PUT /content/some-made-up-url
{
...
"redirects": nil
...
}
```
The intent of the user of the API is clear here - they want no redirects.
However, ContentItem has a default value for redirects:
```
field :redirects, type: Array, default: []
```
And the rest of the content-store expects this value to be an Array, not to be nil.
By passing in potentially nil values in  assign_attributes we allow a situation where fields that …
=> Don't override default attributes with nil

.dockerignore, .gitignore, app/lib/mongo_exporter.rb, spec/lib/mongo_exporter_spec.rb
In staging, when run as part of the Kubernetes CronJob [content-store-mongo-to-postgres-cron](https://github.com/alphagov/govuk-helm-charts/blob/main/charts/govuk-jobs/templates/content-store-mongo-to-postgres-cronjob.yaml) the job fails with this error -
`'The node was low on resource: ephemeral-storage. '`
- i.e. the node it was running on, ran out of storage space (see [discussion on slack](https://gds.slack.com/archives/C013F737737/p1693301007257509))
This PR pipes all files produced by the  `mongo:export` rake tasks through gzip, which produces pretty good compression on the largest collections (content_items particularly) and should drastically cut down the amount of ephemeral storage it needs.
[Trello card](https://trello.com/c/U4kiudWW/820-fix) , see also #1139
This application is …
=> Gzip Mongo exports

db/schema.rb
Imports from MongoDB in staging are failing with the error:
```
PG::NotNullViolation: ERROR:  null value in column "created_at" of relation "content_items" violates not-null constraint
DETAIL:  Failing row contains (03e5fbb1-b59e-44ca-9f66-62349ecd96bf, /, f3bbdec2-0e62-4520-a7fd-6ffd5d36e03a, GOV.UK homepage, {"value": ""}, homepage, , other, other, other, other, , , finding, homepage, en, 2016-02-26 11:53:52, 2023-06-28 09:32:34, null, null, {}, special-route-publisher, frontend, [{"path": "/", "type": "exact"}], [], {"organisations": [{"links": {}, "title": "Government Digital Se..., {}, {}, live, null, 64696791, {}, 21-1687944754.231-10.13.31.76-382, null, 2023-07-21 14:28:36.562, null).
```
However, the same data can be imported fine on integration. 
On investigation, there were two …
=> Re-allow null timestamps on content_items, publish_intents & scheduled_publishing_log_entries

db/migrate/20230830093643_allow_null_timestamps.rb, db/schema.rb
Addendum to #1140 - adding the migration file this time
=> (re-)Allow null timestamps on records imported from mongo

app/lib/mongo_exporter.rb, spec/lib/mongo_exporter_spec.rb
Since adding a pipe through gzip to the mongo export task in #1138, although the CronJob has been completing without errors, it has not actually been exporting anything. Investigation reveals that the way we're executing the command (with Kernel.system) doesn't like the pipe, and this results in the `mongoexport` command failing, but the error is caught by the `system` call and not bubbled out (it just returns a `nil` value).
[Trello card](https://trello.com/c/sxWnwtoO/822-fix-silent-failure-in-content-store-mongo-export)
This PR changes the way we execute the command to use backticks around a plain string, which 
a) works well in local tests under govuk-docker, and
b) raises an exception if the command returns an error status
This application is owned by the publishing platform team. …
=> FIx silent failure in mongoexport call

app/models/route_set.rb, spec/models/route_set_spec.rb
`items.redirects` can sometimes be `nil`. Therefore we need to convert it to an array (even if empty) before doing `map`, else we get an error as `nil` does not have a `map` method.
This will resolve an issue in production where we are unable to unpublish former redirects.
[Trello card](https://trello.com/c/04oigyvM)
=> Fix issue with former redirects being unable to be unpublished

app/lib/find_by_path.rb
[Trello card](https://trello.com/c/fZfTJXrY/866-tune-the-staging-rds-instance-for-content-store-postgresql-branch) 
Benchmarking under sustained load on staging after deploying [content-store-proxy PR #48](https://github.com/alphagov/content-store-proxy/pull/48) showed that we had optimised to the point where the bottleneck was now the PostgreSQL content-store itself (see secondary_response_time in this Kibana screenshot)
Some more benchmarking in a console on the staging pods showed an unexpected slow point in `FindByPath.find()` - the `if matches.any?` call.
On the original Mongoid (main) application, this line is operating on an array, so `any?` is vanishingly fast.
However, in ActiveRecord, this is operating on an `ActiveRecord::Relation`, and it is much slower. Experimentation showed …
=> Speed up FindByPath.find 1000x on K8s/RDS environments

db/migrate/20231016112610_change_scheduled_publishing_delay_seconds_to_bigint.rb, db/schema.rb
…coming through from Whitehall via MongoDB
The overnight mongo-to-postgresql ETL cron job has been failing. Errors in the logs show that an Integer field is overflowing. 
Investigations ([Trello card](https://trello.com/c/hD0M2vAb/867-investigate-failed-mongo-to-postgres-cronjob-in-staging)) found that at least [one content-item](https://www.gov.uk/api/content/government/statistics/announcements/buinsess-population-estimates-2024) has extreme values in a couple of fields:
```
"publishing_scheduled_at": "0024-10-01T00:00:45Z",
"scheduled_publishing_delay_seconds": 63082666703,
```
.... that would mean it is scheduled for publishing at `4022-10-19 23:18:22`
As a result, the `ContentItem.scheduled_publishing_delay_seconds` field to overflow in import.
This PR adds a migration to extend the …
=> fix Integer field overflow in JsonImporter, to handle extreme values

config/environments/production.rb, db/migrate/20231016112610_change_scheduled_publishing_delay_seconds_to_bigint.rb, db/schema.rb
When deploying the migration in #1165 to staging, we found two problems:
1. After running the migration, Rails tried to dump the schema and threw an error with `read-only filesystem - db/schema.rb`
2. While running the migration, PostgreSQL held an exclusive lock for the duration, which was over a minute and a half. This blocked all reads, meaning no requests could go through while the migration was running. This is unacceptable for production.
So this PR:
1. adds the missing `config.dump_schema_after_migration = false` line to production.rb  - it was not needed for the Mongoid application on `main`, but is needed for this ActiveRecord port
2. reworks the migration to minimise table locks, by adding separate steps to add a new column, populate it in small batches,  rename the existing …
=> Rework column type change migration to minimise locks

app/models/content_item.rb, spec/models/content_item_spec.rb
Fixes a [Sentry alert](https://govuk.sentry.io/issues/4561495999/?referrer=slack&notification_uuid=bbcde914-f9b6-4870-86e2-fb3994322648&alert_rule_id=9402830&alert_type=issue) from the draft-content-store-postgresql-branch in production:
```
NoMethodError
undefined method `include?' for nil:NilClass
return true if auth_bypass_ids.include?(auth_bypass_id)
^^^^^^^^^
```
Details in [this Trello card](https://trello.com/c/Qb5DI23q/915-fix-undefined-method-include-for-nil-in-content-store-postgresql-branch)
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your …
=> Fix error when auth_bypass_ids is nil

.github/workflows/ci.yml, .github/workflows/verify-pact.yml, Jenkinsfile, README.md, spec/service_consumers/pact_helper.rb
[Trello card](https://trello.com/c/7f3F6Xij/3338-migrate-from-the-old-paas-based-pact-broker-to-the-new-instance-on-heroku)
We are currently migrating our Pact Broker instance from PaaS to Heroku. `gds-api-adapters` has already been updated to publish pacts to both instances, now we need to update each of our API providers to fetch from the new instance instead of the old one.
=> Update Pact Broker URL

.github/workflows/verify-pact.yml
On the `port-to-postgresql` branch, pact tests were incorrectly reported as successful in CI, even though [no pact tests were actually being run](https://github.com/alphagov/content-store/actions/runs/6878685214/job/18708888824?pr=1173#step:6:25). Errors indicated that this was because they [could not connect to the database](https://github.com/alphagov/content-store/actions/runs/6878685214/job/18708888824?pr=1173#step:6:32).
[Trello card](https://trello.com/c/qA4Xn1jO/935-actually-verify-pacts-in-content-store-ci)
After investigation, it looks like the `setup-postgres` step was [creating a database called `test`](https://github.com/alphagov/content-store/actions/runs/6878685214/job/18708888824?pr=1173#step:2:69), but the pact tests were expecting a database called …
=> Fix postgresql pact tests

.github/workflows/ci.yml, .github/workflows/verify-pact.yml, Jenkinsfile, README.md, spec/service_consumers/pact_helper.rb
This is a (discovered-the-hard-way) clone of [James's pull request that was merged into `main` a few weeks ago](https://github.com/alphagov/content-store/pull/1172).
> [Trello card](https://trello.com/c/7f3F6Xij/3338-migrate-from-the-old-paas-based-pact-broker-to-the-new-instance-on-heroku)
>
> We are currently migrating our Pact Broker instance from PaaS to Heroku. gds-api-adapters has already been updated to publish pacts to both instances, now we need to update each of our API providers to fetch from the new instance instead of the old one.
What he said ^ but in past tense.
=> Update Pact Broker URL for `port-to-postgresql` branch

.github/workflows/ci.yml
This is a clone of https://github.com/alphagov/content-store/pull/1183 but that was targetting `main` and this is targetting the `port-to-postgresql` branch
=> Add CodeQL (SAST) scan and Dependency Review (SCA) scan to CI pipeline (for `port-to-postgresql` branch)

config/initializers/logstasher.rb
https://trello.com/c/jDSDGNyn/814-measure-and-record-our-publishing-latency-sli
It turns out that you can't call `LogStasher.add_custom_fields` twice. Because Content Store's custom fields config was being run after the govuk_app_config gem's own custom fields config, the gem's config was being overwritten. So, fields like `govuk_request_id` and `varnish_id` weren't appearing in Content Store's controller request logs (but `govuk_dependency_resolution_source_content_id` was).
The gem (version 9.7.0) now provides a mechanism for setting custom fields that doesn't overwrite the gem's own settings https://docs.publishing.service.gov.uk/repos/govuk_app_config.html#logger-configuration:
```
GovukJsonLogging.configure do
add_custom_fields do |fields|
fields[:govuk_custom_field] = …
```
=> Fix logger custom field config

README.md
Merging the very long-running `port-to-postgresql` branch back into main is going to take longer than originally thought, to make sure that the commit history ends up reasonably comprehensible and manageable. 
Until we finish this, deployment will remain a non-standard task that requires specific knowledge. So for the benefit of anyone who needs to make an urgent change when I'm not around, I've added this note into the README. 
Follow [these …
=> add note about how to deploy into the README

README.md
Remove the temporary note added in #1194 about how to deploy while we were in a transitional, non-main state.
Since merging #1085 this note is no longer needed or wanted.
[Trello card](https://trello.com/c/sQIA1Q7d/977-update-all-content-store-documentation-relevant-to-mongo-postgres-switch)
=> Remove README note about deployment in transitional state

config/routes.rb
The healthcheck endpoint was still checking Mongoid - this needs* switching to ActiveRecord.
[Trello card](https://trello.com/c/dggI2ttX/988-remove-any-now-redundant-mongo-related-code-from-content-store)
*One for later - as this has been reporting a critical status for weeks but no-one noticed - is this endpoint even used anymore? 
=> Switch the /healthcheck/ready endpoint to check ActiveRecord

Gemfile, Gemfile.lock
This gem is not being initialised in the `test_helper.rb` file, so therefore is not being used and can be removed.
=> Remove `simplecov-rcov` gem dependency

db/migrate/20240220151333_remove_worldwide_offices.rb, db/schema.rb
Worldwide Offices are now represented within the Worldwide Organisation content item.
Therefore we no longer need these content items.
We cannot use the standard means of removing these items (e.g. marking them as gone), as the route has been re-registered by the Worldwide Organisation in https://github.com/alphagov/whitehall/pull/8853.
Depends on: https://github.com/alphagov/whitehall/pull/8859.
[Trello card](https://trello.com/c/9ivR4TGQ)
=> Add migration to delete worldwide offices

db/migrate/20240312132747_remove_whitehall_frontend.rb, db/schema.rb
Whitehall Frontend was switched off in 2023. However, as a result of [a bug](https://trello.com/c/z5pHDAXC) where some documents were missed when they were bulk republished, a small number (approximately 65) of documents remained in the Content Store database with a rendering app of `whitehall-frontend` and a schema name of `placeholder`.
The logic to deal with placeholders was removed in https://github.com/alphagov/content-store/pull/1152, therefore the routes were never registered for these content items (and never will be, as Content Store assumes they have already been rendered).
Since the public versions of these page already return a 404 or 500 error (or in some cases, have a redirect implemented directly in Router), it is safe to remove them and republish the affected pages from …
=> Remove all content items rendered by Whitehall Frontend

spec/integration/fetching_content_item_spec.rb
This test (which simply makes a GET request on the content item endpoint) was testing whether the returned content item included a `public_updated_at` time that was within one second of now.
This relied on the record being created within 1 second of the GET request being made by the test, therefore sometimes failing.
However we are not testing the creation of the record here, so it is not required to check the timestamp.
=> Remove unnecessary flaky assertion

config/application.rb
This application has been using Rails 7.1 for many months now, so it is safe to migrate the cache format version to the default for 7.1, since we won't be rolling back to 7.0.
[Trello card](https://trello.com/c/KtQiL6h1)
=> Update cache format version for Rails 7.1

app/models/publish_intent.rb, lib/tasks/housekeeping.rake, spec/models/publish_intent_spec.rb
We use publish intents for schedule publishing to reduce the cache time ahead of publication. However, once the associated content items is published we don’t need the intent anymore.
Looks like from the [code we only delete intents if we unschedule something](https://github.com/search?q=org%3Aalphagov+destroy_intent++NOT+is%3Aarchived+NOT+path%3A%2F%5Etest%5C%2F%2F+NOT+path%3A%2F%5Espec%5C%2F%2F&type=code) - but we should also be delete them them when we publish the content item.
The number of Publish Intents has impact on the performance for route reloading in Router. Currently we have t[o scan (do an anti-join)](https://github.com/alphagov/router/blob/42a55aba7060bee3b0edb80f1b2602ccb0bc5d70/lib/sql/routes.sql#L30) through all the publish intents for routes - obviously that’d be far …
=> Add rake task to remove old publishing intents

db/migrate/20241209132444_update_notify_trigger_for_route_changes.rb, db/structure.sql, spec/integration/notify_route_change_spec.rb
Currently, we send a notification to the Router to update route tables whenever there is any change to the content_items (or publish_intents) tables. However, the Router only needs to update the route table when changes affect specific columns that determine the routes.
This change should reduce unnecessary reloading.
=> Notify Router only on specific column updates

config/application.rb
References to Router API have actually been removed from version 98.0.0 of GDS API Adapters.
The uses of Router API were recently removed from this codebase, but I guess this was overlooked.
=> Remove import of (deprecated) gds_api/router

Gemfile, Gemfile.lock, openapi.yaml, spec/lib/validate_openapi3_definition_spec.rb
The OpenAPI 3.0 definition was invalid. This can be confirmed by using tools such as the [Swagger Editor](https://editor.swagger.io/) or by looking at an example of where this data was consumed (e.g. [GOV.UK Content API docs](https://content-api.publishing.service.gov.uk/reference.html#contentitem)).
Updating to make this definition valid and adding a test so we don't accidentally make the definition invalid in the future.
[Trello card](https://trello.com/c/7LqhcraV)
=> Fix OpenAPI 3.0 definition

app/controllers/content_items_controller.rb, spec/integration/fetching_content_item_spec.rb
This allows us to look at the performance of retrieving individual document types from content_store. Currently the monitoring does not distinquish between types.
Done as part of the graphql work so we can compare performance of document types between graphl and regular content-store.
=> Add document_type and Schema_name to prometheus labels

docs/content-store-api.md
This is referenced in the final paragraph, but is never introduced and relies on the reader knowing what 'Content API' actually is.
Also makes a few other changes to the internal API documentation, to tidy the document and fix some incorrect information.
=> Add introduction to 'Content API' in the API documentation

db/structure.sql, lib/tasks/add_additional_fields_to_local_transactions.rake
- Ideally, we would be able to deploy this through the Publisher UI. However, due to the PG change freeze, that might not be possible until later in August.
- Once the UI version of Publisher is available, we can simply republish the changes through the UI and remove this task.
https://trello.com/c/3ZomQTGq/753-update-find-a-registered-childminder-postcode-finder
=> temp: Add task to update two local transactions in place
